/**
 * One full build at a time over this working tree.
 *
 * `npm run compile`'s clean step wipes all of `out/` and `media/`, so two build chains running
 * concurrently (a bat started twice, or a bat racing a manually invoked npm script) clobber
 * each other's artifacts mid-flight — tests fail with ENOENT on files they read seconds ago,
 * and the addon copy fails with EBUSY while another run's test workers hold the binary.
 * The build bats hold this lock for their whole run and release it on every exit path.
 *
 *   node scripts/build-lock.mjs hold <token>     # wait (with progress notes) until acquired
 *   node scripts/build-lock.mjs release <token>  # release, but only if <token> still owns it
 *
 * The token is generated by each bat run; the lock records it next to the holding process's
 * pid, so a lock left behind by a killed terminal (no release ran) is stolen automatically
 * once its process is gone, and a release from an superseded run cannot free a newer owner's
 * lock. GGR_LOCK_MAX_WAIT_MS overrides how long `hold` waits (default 15 minutes);
 * GGR_BUILD_LOCK_DIR overrides where the lock lives (tests point it at a sandbox).
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const lockDir = process.env.GGR_BUILD_LOCK_DIR ?? path.join(os.tmpdir(), 'git-graph-rs-build.lock');
const ownerFile = path.join(lockDir, 'owner');
const MAX_WAIT_MS = Number(process.env.GGR_LOCK_MAX_WAIT_MS ?? 15 * 60 * 1000);

function sleepSync(ms) {
	Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

/** A pid is alive when signal 0 is deliverable (EPERM counts: exists, not ours). */
function processExists(pid) {
	try {
		process.kill(pid, 0);
		return true;
	} catch (error) {
		return error.code === 'EPERM';
	}
}

/** Read the lock's owner as { pid, token }, or null when unreadable. */
function readOwner() {
	try {
		const [pid, token] = fs.readFileSync(ownerFile, 'utf8').trim().split(' ');
		const pidNumber = Number(pid);
		if (!Number.isInteger(pidNumber) || pidNumber <= 0) return null;
		return { pid: pidNumber, token: token ?? '' };
	} catch {
		return null;
	}
}

/** Atomically take the lock; false when somebody already holds it. */
function tryAcquire(token) {
	try {
		fs.mkdirSync(lockDir);
	} catch (error) {
		if (error.code === 'EEXIST') return false;
		throw error;
	}
	// The liveness pid is the PARENT (the cmd.exe running the build bat), not this helper —
	// the helper exits the moment it acquires, and a lock "held" by a dead pid would be
	// stolen instantly, defeating the mutual exclusion.
	fs.writeFileSync(ownerFile, `${process.ppid ?? process.pid} ${token}`);
	return true;
}

/** Remove a lock whose holding process has died; true when the lock was stolen. */
function stealIfDead() {
	const owner = readOwner();
	if (owner === null || processExists(owner.pid)) return false;
	fs.rmSync(lockDir, { recursive: true, force: true });
	return true;
}

function hold(token) {
	const start = Date.now();
	let lastNote = 0;
	while (!tryAcquire(token)) {
		if (stealIfDead()) continue;
		if (Date.now() - start > MAX_WAIT_MS) {
			const owner = readOwner();
			console.error(
				`! Timed out waiting for the build lock (held by PID ${owner?.pid ?? '?'} since ` +
					`more than ${Math.round(MAX_WAIT_MS / 60000)} minutes). If that build is gone, ` +
					`remove ${lockDir} and try again.`
			);
			process.exit(1);
		}
		if (Date.now() - lastNote >= 10000) {
			const owner = readOwner();
			console.log(`  waiting: another git-graph-rs build (PID ${owner?.pid ?? '?'}) is still running...`);
			lastNote = Date.now();
		}
		sleepSync(1000);
	}
}

/** Release only when the caller's token still owns the lock. */
function release(token) {
	const owner = readOwner();
	if (owner !== null && owner.token === token) {
		fs.rmSync(lockDir, { recursive: true, force: true });
	}
}

const command = process.argv[2];
const token = process.argv[3] ?? '';
if (command === 'hold' && token !== '') hold(token);
else if (command === 'release' && token !== '') release(token);
else {
	console.error('Usage: node scripts/build-lock.mjs hold|release <token>');
	process.exit(1);
}
