/**
 * Localised strings for the Git Graph View webview.
 *
 * The web sources are non-module scripts concatenated into a single IIFE, so the
 * declarations below are global: every web source can reference `strings.<key>`
 * directly, and `setInterfaceLanguage` (called by web/main.ts during start-up,
 * with the `git-graph-rs.interfaceLanguage` setting forwarded by the extension
 * host) switches the dictionary. Because a configuration change reloads the
 * webview, the language is applied before anything is rendered.
 */

const STRINGS_EN = {
	/* Toolbar & header */
	repoLabel: 'Repo: ',
	branchesLabel: 'Branches: ',
	authorsLabel: 'Authors: ',
	showRemoteBranchesLabel: 'Remote',
	showRemoteBranchesTitle: 'Show Remote Branches: display remote branches in the graph',
	scrollToHeadTitle: 'Scroll to the commit referenced by HEAD',
	findTitle: 'Find',
	filterTitle: 'Filter Commits by Path',
	filterTitleActive: 'Filter Commits by Path (active: {0})',
	terminalTitle: 'Open a Terminal for this Repository',
	settingsTitle: 'Settings',
	fetchTitle: 'Fetch from Remote(s)',
	fetchAndPruneTitle: 'Fetch & Prune from Remote(s)',
	refreshTitle: 'Refresh',
	refreshingTitle: 'Refreshing',
	pinnedLabel: 'Pinned: ',
	pinnedBranchChipTitle: 'Show only branch {0} (click ✕ to unpin)',
	pinnedUnpinBranch: 'Unpin branch {0}',
	pinnedCommitChipTitle: 'Jump to commit {0} (click ✕ to unpin)',
	pinnedUnpinCommit: 'Unpin commit {0}',
	pinnedBadgeTitle: 'Pinned commit',

	/* Dropdown defaults */
	dropdownRepos: 'Repos',
	dropdownBranches: 'Branches',
	dropdownAuthors: 'Authors',

	/* Find Widget */
	findPlaceholder: 'Find',
	findMatchCase: 'Match Case',
	findUseRegex: 'Use Regular Expression',
	findPrevMatch: 'Previous match (Shift+Enter)',
	findNextMatch: 'Next match (Enter)',
	findOpenCdv: 'Open the Commit Details View for the current match',
	findClose: 'Close (Escape)',
	findNoResults: 'No Results',
	findPositionOf: '{0} of {1}',

	/* Dialogs (common buttons & messages) */
	dialogCancel: 'Cancel',
	dialogClose: 'Close',
	dialogDismiss: 'Dismiss',
	dialogApply: 'Apply',
	dialogClearFilter: 'Clear Filter',
	dialogErrorPrefix: 'Error: ',
	dialogUnableToAction: 'Unable to {0}, one or more invalid characters entered.',
	filterByPathMessage: 'Filter the commits by a file path:',
	filterPathName: 'Path',
	filterPathPlaceholder: 'e.g. src/main.ts, web/ (comma-separated paths; commits changing any of them are shown)',

	/* Data loss risk warnings (shown before running operations that can destroy data) */
	dataLossDialogTitle: 'Data Loss Risk',
	dataLossContinue: 'Yes, I understand the risk',
	dataLossMascotCaption: 'My, what a bold little risk-taker you are!',
	riskResetHard: 'A hard reset will <b>permanently discard all uncommitted changes</b> (staged and unstaged) in the working tree. Uncommitted changes cannot be recovered.',
	riskCleanUntrackedFiles: 'Cleaning will <b>permanently delete all untracked files</b> from the working directory.',
	riskCleanUntrackedDirectories: 'Cleaning will <b>permanently delete all untracked files and directories</b> from the working directory.',
	riskCleanUntrackedSuffix: 'Deleted files are not moved to the trash and cannot be recovered.',
	riskDeleteBranchForce: 'Force deleting the branch <b>{0}</b> can make commits that are only reachable from it unreachable, and Git may permanently remove them.',
	riskDeleteBranchRemote: 'Deleting the branch on {0} removes it for all collaborators of the repository.',
	riskDeleteRemoteBranch: 'Deleting the remote branch <b>{0}</b> removes it from the remote repository for all collaborators. Commits that are only reachable from this branch may be permanently lost.',
	riskPushForce: 'Force pushing will <b>overwrite the remote branch {0}</b>. Commits on the remote that are not present locally can be permanently lost.',
	riskPushForceWithLease: 'Force pushing with lease will <b>overwrite the remote branch {0}</b> if it has not changed on the remote. Commits on the remote that are not present locally can be permanently lost.',
	riskFetchIntoLocalBranchForce: 'Force updating will <b>reset the local branch {0} to the remote branch</b>, discarding all local commits that are not on the remote.',
	riskDropCommit: 'Dropping this commit rewrites the history of the current branch without it. The dropped commit is only recoverable via the reflog.',
	riskDropStash: 'Dropping this stash <b>permanently removes the stashed changes</b>. If they have not been applied elsewhere, they cannot be recovered.',
	riskResetFile: 'Resetting <b>{0}</b> will <b>permanently discard any uncommitted changes</b> made to this file in the working tree.',

	/* Context menus - commits */
	menuCheckoutBranch: 'Checkout Branch',
	menuCompareWith: 'Compare with...',
	menuCheckout: 'Checkout',
	menuAddTag: 'Add Tag',
	menuCreateBranch: 'Create Branch',
	menuCherryPick: 'Cherry Pick',
	menuRevert: 'Revert',
	menuDrop: 'Drop',
	menuMergeIntoCurrentBranch: 'Merge into current branch',
	menuRebaseOnBranch: 'Rebase current branch on Branch',
	menuRebaseOnCommit: 'Rebase current branch on this Commit',
	menuResetToCommit: 'Reset current branch to this Commit',
	menuResetLastCommitSoft: 'Reset Last Commit (Soft)',
	menuEditMessage: 'Edit Message',
	menuPushBranch: 'Push Branch',
	menuPullBranch: 'Pull Branch',
	menuPullIntoCurrentBranch: 'Pull into current branch',
	menuCopyCommitHash: 'Copy Commit Hash to Clipboard',
	menuCopyCommitSubject: 'Copy Commit Subject to Clipboard',
	menuSelectForCompare: 'Select for Compare',
	menuCompareWithSelected: 'Compare with Selected Commit',
	menuDiffWithWorkingTree: 'Diff with Working Tree',

	/* Context menus - branches & remotes */
	menuRenameBranch: 'Rename Branch',
	menuDeleteBranch: 'Delete Branch',
	menuDeleteRemoteBranch: 'Delete Remote Branch',
	menuFetchIntoLocalBranch: 'Fetch into local branch',
	menuCreatePullRequest: 'Create Pull Request',
	menuCreateArchive: 'Create Archive',
	menuSelectInBranchesDropdown: 'Select in Branches Dropdown',
	menuUnselectInBranchesDropdown: 'Unselect in Branches Dropdown',
	menuCopyBranchName: 'Copy Branch Name to Clipboard',
	menuViewIssue: 'View Issue',

	/* Context menus - stashes, tags & uncommitted changes */
	menuApplyStash: 'Apply Stash',
	menuCreateBranchFromStash: 'Create Branch from Stash',
	menuPopStash: 'Pop Stash',
	menuDropStash: 'Drop Stash',
	menuCopyStashName: 'Copy Stash Name to Clipboard',
	menuCopyStashHash: 'Copy Stash Hash to Clipboard',
	menuViewDetails: 'View Details',
	menuDeleteTag: 'Delete Tag',
	menuPushTag: 'Push Tag',
	menuCopyTagName: 'Copy Tag Name to Clipboard',
	menuStashUncommitted: 'Stash uncommitted changes',
	menuResetUncommitted: 'Reset uncommitted changes',
	menuCleanUntracked: 'Clean untracked files',
	menuOpenSourceControlView: 'Open Source Control View',


	/* Settings Widget */
	settingsSectionGeneral: 'General',
	settingsNameLabel: 'Name:',
	settingsNameDefault: ' (Default Name from the File System)',
	settingsEditNameTitle: 'Edit Name',
	settingsDeleteNameTitle: 'Delete Name',
	settingsInitialBranchesLabel: 'Initial Branches:',
	settingsCheckedOut: 'Checked Out',
	settingsShowAll: 'Show All',
	settingsLocal: 'Local',
	settingsGlobal: 'Global',
	settingsEditInitialBranchesTitle: 'Edit Initial Branches',
	settingsClearInitialBranchesTitle: 'Clear Initial Branches',
	settingsShowStashes: 'Show Stashes',
	settingsShowTags: 'Show Tags',
	settingsIncludeReflogs: 'Include commits only mentioned by reflogs',
	settingsIncludeReflogsInfo: 'Only applies when showing all branches.',
	settingsOnlyFirstParent: 'Only follow the first parent of commits',
	settingsOnlyFirstParentInfo: 'Instead of following all parents of commits, only follow the first parent when discovering the commits to load.',
	settingsInterfaceLanguageLabel: 'Interface Language:',
	settingsLanguageAuto: 'Auto (follows Visual Studio Code)',
	settingsLanguageEnglish: 'English',
	settingsLanguageChinese: '\u4e2d\u6587\uff08\u7b80\u4f53\uff09',
	settingsNameDialogMessage: 'Specify a Name for this Repository:',
	settingsNameInput: 'Name',
	settingsNameDialogSave: 'Save Name',
	settingsDeleteNameConfirm: 'Are you sure you want to delete the manually configured name <b><i>{0}</i></b> for this repository, and use the default name from the File System <b><i>{1}</i></b>?',
	settingsYesDelete: 'Yes, delete',
	settingsInitialBranchesDialogHeader: '<b>Configure Initial Branches</b>',
	settingsInitialBranchesDialogText: 'Configure the branches that are initially shown when this repository is loaded in the Git Graph View.',
	settingsInitialBranchesDialogNote: 'Note: When "Checked Out Branch" is Disabled, and no "Specific Branches" are selected, all branches will be shown.',
	settingsInitialBranchesCheckedOutInput: 'Checked Out Branch',
	settingsInitialBranchesSpecificInput: 'Specific Branches',
	settingsSaveConfiguration: 'Save Configuration',
	settingsClearInitialBranchesConfirm: 'Are you sure you want to clear the branches that are initially shown when this repository is loaded in the Git Graph View?',
	settingsYesClear: 'Yes, clear',
	settingsNotSet: 'Not Set',

	settingsSectionUserDetails: 'User Details',
	settingsUserNameLabel: 'User Name:',
	settingsUserEmailLabel: 'User Email:',
	settingsEdit: 'Edit',
	settingsRemove: 'Remove',
	settingsUserDetailsIntro: 'User Details (such as name and email) are used by Git to record the Author and Committer of commit objects.',
	settingsAddUserDetails: 'Add User Details',
	settingsUserDetailsDialogMessage: 'Set the user name and email used by Git to record the Author and Committer of commit objects:',
	settingsUserNameInput: 'User Name',
	settingsUserEmailInput: 'User Email',
	settingsUseGlobally: 'Use Globally',
	settingsUseGloballyInfo: 'Use the "User Name" and "User Email" globally for all Git repositories (it can be overridden per repository).',
	settingsSetUserDetails: 'Set User Details',
	settingsSettingUserDetails: 'Setting User Details',
	settingsGlobally: 'globally',
	settingsLocally: 'locally',
	settingsRemoveUserDetailsConfirm: 'Are you sure you want to remove the <b>{0} configured</b> user name and email, which are used by Git to record the Author and Committer of commit objects?',
	settingsYesRemove: 'Yes, remove',
	settingsRemovingUserDetails: 'Removing User Details',

	settingsSectionRemotes: 'Remote Configuration',
	settingsRemote: 'Remote',
	settingsUrl: 'URL',
	settingsType: 'Type',
	settingsAction: 'Action',
	settingsFetch: 'Fetch',
	settingsPush: 'Push',
	settingsShowRemoteTitle: 'Click to show branches of this remote.',
	settingsHideRemoteTitle: 'Click to hide branches of this remote.',
	settingsFetchFromRemoteTitle: 'Fetch from Remote',
	settingsPruneRemoteTitle: 'Prune Remote',
	settingsEditRemoteTitle: 'Edit Remote',
	settingsDeleteRemoteTitle: 'Delete Remote',
	settingsNoRemotes: 'There are no remotes configured for this repository.',
	settingsAddRemote: 'Add Remote',
	settingsAddRemoteDialogMessage: 'Add a new remote to this repository:',
	settingsFetchUrlInput: 'Fetch URL',
	settingsPushUrlInput: 'Push URL',
	settingsPushUrlPlaceholder: 'Leave blank to use the Fetch URL',
	settingsFetchImmediately: 'Fetch Immediately',
	settingsAddingRemote: 'Adding Remote',
	settingsEditRemoteDialogMessage: 'Edit the remote <b><i>{0}</i></b>:',
	settingsSaveChanges: 'Save Changes',
	settingsSavingRemoteChanges: 'Saving Changes to Remote',
	settingsDeleteRemoteConfirm: 'Are you sure you want to delete the remote <b><i>{0}</i></b>?',
	settingsDeletingRemote: 'Deleting Remote',
	settingsFetchRemoteConfirm: 'Are you sure you want to fetch from the remote <b><i>{0}</i></b>?',
	settingsPrune: 'Prune',
	settingsPruneInfo: 'Before fetching, remove any remote-tracking references that no longer exist on the remote.',
	settingsPruneTags: 'Prune Tags',
	settingsPruneTagsInfo: 'Before fetching, remove any local tags that no longer exist on the remote. Requires Git >= 2.17.0, and "Prune" to be enabled.',
	settingsYesFetch: 'Yes, fetch',
	settingsFetchingFromRemote: 'Fetching from Remote',
	settingsPruneRemoteConfirm: 'Are you sure you want to prune remote-tracking references that no longer exist on the remote <b><i>{0}</i></b>?',
	settingsYesPrune: 'Yes, prune',
	settingsPruningRemote: 'Pruning Remote',

	settingsSave: 'Save',
	settingsBack: 'Back',
	settingsGoBack: 'Go Back',
	settingsYesHide: 'Yes, hide',

	settingsSectionIssueLinking: 'Issue Linking',
	settingsIssueRegexLabel: 'Issue Regex:',
	settingsIssueUrlLabel: 'Issue URL:',
	settingsIssueLinkingIntro: 'Issue Linking converts issue numbers in commit &amp; tag messages into hyperlinks, that open the issue in your issue tracking system. If a branch\'s name contains an issue number, the issue can be viewed via the branch\'s context menu.',
	settingsAddIssueLinking: 'Add Issue Linking',
	settingsEditIssueLinkingHeader: '<b>Edit Issue Linking for this Repository</b>',
	settingsAddIssueLinkingHeader: '<b>Add Issue Linking to this Repository</b>',
	settingsIssueExampleText: 'The following example links <b>#123</b> in commit messages to <b>https://github.com/your-org/your-repo/issues/123</b>:',
	settingsIssueRegexDetected: 'The prefilled Issue Regex was detected in commit messages in this repository. Review and/or correct it if necessary.',
	settingsIssueRegexInput: 'Issue Regex',
	settingsIssueRegexInfo: 'A regular expression that matches your issue numbers, with one or more capturing groups ( ) that will be substituted into the "Issue URL".',
	settingsIssueUrlInput: 'Issue URL',
	settingsIssueUrlInfo: 'The issue\'s URL in your issue tracking system, with placeholders ($1, $2, etc.) for the groups captured ( ) in the "Issue Regex".',
	settingsUseGloballyIssueInfo: 'Use the "Issue Regex" and "Issue URL" for all repositories by default (it can be overridden per repository). Note: "Use Globally" is only suitable if identical Issue Linking applies to the majority of your repositories (e.g. when using JIRA or Pivotal Tracker).',
	settingsInvalidIssueRegex: 'Invalid Issue Regex',
	settingsIssueRegexNoGroup: 'The regular expression does not contain a capturing group ( ).',
	settingsInvalidIssueUrl: 'Invalid Issue URL',
	settingsIssueUrlNoPlaceholders: 'The Issue URL does not contain any placeholders ($1, $2, etc.) for the issue number components captured in the Issue Regex.',
	settingsRemoveConfirmPrefix: 'Are you sure you want to remove ',
	settingsRemoveIssueLinkingLocal: 'the <b>locally configured</b> ',
	settingsRemoveIssueLinkingFromRepo: 'Issue Linking from this repository',
	settingsRemoveIssueLinkingGlobal: 'the <b>globally configured</b> Issue Linking in Git Graph',

	settingsSectionPullRequest: 'Pull Request Creation',
	settingsProviderLabel: 'Provider:',
	settingsSourceRepoLabel: 'Source Repo:',
	settingsDestinationRepoLabel: 'Destination Repo:',
	settingsDestinationBranchLabel: 'Destination Branch:',
	settingsPrIntro: 'Pull Request Creation automates the opening and pre-filling of a Pull Request form, directly from a branch\'s context menu.',
	settingsConfigurePrIntegration: 'Configure "Pull Request Creation" Integration',
	settingsUnableToConfigurePr: 'Unable to configure the "Pull Request Creation" Integration',
	settingsPrNeedsRemote: 'The repository must have at least one remote to configure the "Pull Request Creation" Integration. There are no remotes in the current repository.',
	settingsPrDialog1Header: 'Configure "Pull Request Creation" Integration (Step&nbsp;1/2)',
	settingsPrDialog2Header: 'Configure "Pull Request Creation" Integration (Step&nbsp;2/2)',
	settingsPrProviderInput: 'Provider',
	settingsPrProviderInfo: 'In addition to the built-in publicly hosted Pull Request providers, custom providers can be configured using the Extension Setting "git-graph-rs.customPullRequestProviders" (e.g. for use with privately hosted Pull Request providers).',
	settingsPrSourceRemoteInput: 'Source Remote',
	settingsPrSourceRemoteInfo: 'The remote that corresponds to the source of the Pull Request.',
	settingsPrDestRemoteInput: 'Destination Remote',
	settingsPrDestRemoteInfo: 'The remote that corresponds to the destination / target of the Pull Request.',
	settingsNotARemote: 'Not a remote',
	settingsNext: 'Next',
	settingsHostRootUrlInput: 'Host Root URL',
	settingsHostRootUrlInfo: 'The Pull Request provider\'s Host Root URL (e.g. https://github.com).',
	settingsSourceOwnerInput: 'Source Owner',
	settingsSourceOwnerInfo: 'The owner of the repository that is the source of the Pull Request.',
	settingsSourceRepoInput: 'Source Repo',
	settingsSourceRepoInfo: 'The name of the repository that is the source of the Pull Request.',
	settingsDestOwnerInput: 'Destination Owner',
	settingsDestOwnerInfo: 'The owner of the repository that is the destination / target of the Pull Request.',
	settingsDestRepoInput: 'Destination Repo',
	settingsDestRepoInfo: 'The name of the repository that is the destination / target of the Pull Request.',
	settingsDestProjectIdInput: 'Destination Project ID',
	settingsDestProjectIdInfo: 'The GitLab Project ID of the destination / target of the Pull Request. Leave this field blank to use the default destination / target configured in GitLab.',
	settingsDestBranchInput: 'Destination Branch',
	settingsDestBranchInfo: 'The name of the branch that is the destination / target of the Pull Request.',
	settingsRemovePrConfirm: 'Are you sure you want to remove the configured "Pull Request Creation" Integration?',

	/* Repository Settings > Gerrit */
	settingsSectionGerrit: 'Gerrit Change Refs',
	settingsGerritFetchRefs: 'Fetch Gerrit change refs (refs/changes/*)',
	settingsGerritFetchRefsInfo: 'Fetch the most recent Gerrit changes into refs/remotes/<gerrit.remote>/changes/ (the latest patchset and the NoteDb meta ref of each, as many as the fetch limit allows - set it below, or globally via the git-graph-rs.gerrit.fetchLimit setting). Commits belonging to a change get a change badge - click it to see the review information. Unchecking deletes the locally fetched change refs and stops the fetching.',
	settingsGerritStatusFilterLabel: 'Show changes with status:',
	settingsGerritStatusOpen: 'Open',
	settingsGerritStatusMerged: 'Merged',
	settingsGerritStatusAbandoned: 'Abandoned',
	settingsGerritStatusWip: 'Work in Progress',
	settingsGerritDisableConfirm: 'Are you sure you want to disable the fetching of Gerrit change refs?<br><span class="messageContent">All locally fetched change refs (refs/remotes/&lt;gerrit.remote&gt;/changes/*) will be deleted. The downloaded commits remain in the object database until Git garbage collects them.</span>',
	settingsGerritDisableAction: 'Yes, disable',
	settingsGerritEnabling: 'Enabling Gerrit change ref fetching',
	settingsGerritClearing: 'Deleting Gerrit change refs',
	errGerritSetFetchRefs: 'Unable to change the Gerrit change ref fetching',

	/* Gerrit change badge & review dialog */
	gerritBadgeTitle: 'Gerrit Change #{0}/{1} - click for the review details',
	gerritChangeHeader: 'Gerrit Change #{0}',
	gerritPatchSetLabel: 'Patch Set {0}',
	gerritOwnerLabel: 'Owner: {0}',
	gerritOpenInGerrit: 'Open in Gerrit',
	gerritCodeReviewLabel: 'Code-Review',
	gerritVerifiedLabel: 'Verified',
	gerritStatusOpen: 'Open (awaiting review)',
	gerritStatusMerged: 'Merged',
	gerritStatusAbandoned: 'Abandoned',
	gerritStatusWip: 'Work in Progress',
	gerritReviewDialogTitle: 'Gerrit Review',
	gerritNoReviewInfo: 'No Gerrit review information is available for this commit. Only commits of changes whose NoteDb meta ref was parsed have review information.',
	gerritToggleNoteDb: 'Click to toggle the full NoteDb record of this event',
	gerritEventsHint: 'Click an event to show its full NoteDb record (patchset, commit hash, labels and status footers).',
	gerritTimelineLabel: 'Review Activity',
	gerritEventsPending: 'The review activity is still being loaded …',
	settingsGerritFetchLimitLabel: 'Fetch limit',
	settingsGerritFetchLimitInfo: 'How many of the most recent Gerrit changes are fetched into refs/remotes/<gerrit.remote>/changes/ (the latest patchset and the NoteDb meta ref of each). Range 1–10000; leaving the input empty follows the git-graph-rs.gerrit.fetchLimit setting.',
	settingsGerritFetchLimitEditTitle: 'Edit the Gerrit fetch limit',
	settingsGerritFetchLimitInput: 'Changes to fetch',
	settingsGerritFetchLimitPlaceholder: 'empty = the global setting',
	settingsGerritFetchLimitGlobal: 'Global setting ({0})',

	/* Settings columns */
	settingsColumnRepo: 'Repository Settings',
	settingsColumnRepoHint: 'Applies to the repository currently open in this view',
	settingsColumnGlobal: 'Global Settings',
	settingsColumnGlobalHint: 'Applies to every repository (saved to your VS Code User Settings)',
	settingsSavingSetting: 'Saving Setting',
	settingsUnableToSaveSetting: 'Unable to save the Setting',

	/* Global Settings > Graph & Display */
	settingsSectionGraphDisplay: 'Graph & Display',
	settingsGraphStyleLabel: 'Graph Style:',
	settingsGraphStyleRounded: 'Rounded',
	settingsGraphStyleAngular: 'Angular',
	settingsGraphRowHeightLabel: 'Row Height:',
	settingsGraphFontSizeLabel: 'Font Size:',
	settingsDateTypeLabel: 'Date Shown:',
	settingsDateTypeAuthor: 'Author Date',
	settingsDateTypeCommit: 'Commit Date',
	settingsDateFormatLabel: 'Date Format:',
	settingsDateFormatDateAndTime: 'Date & Time',
	settingsDateFormatDateOnly: 'Date Only',
	settingsDateFormatIsoDateAndTime: 'ISO Date & Time',
	settingsDateFormatIsoDateOnly: 'ISO Date Only',
	settingsDateFormatRelative: 'Relative',
	settingsCombineBranchLabels: 'Combine local & remote branch labels',
	settingsStickyHeader: 'Sticky header while scrolling',
	settingsRenderMarkdown: 'Render Markdown in commit messages',

	/* Global Settings > Commit Loading */
	settingsSectionCommitLoading: 'Commit Loading',
	settingsInitialLoadLabel: 'Initial Load:',
	settingsLoadMoreLabel: 'Load More:',
	settingsCommitsUnit: 'commits',
	settingsLoadMoreAutomatically: 'Load more commits automatically',
	settingsCommitOrderLabel: 'Commit Order:',
	settingsCommitOrderDate: 'Date',
	settingsCommitOrderAuthorDate: 'Author Date',
	settingsCommitOrderTopo: 'Topological',
	settingsFetchAvatars: 'Fetch avatars of commit authors',
	settingsShowUncommittedChanges: 'Show Uncommitted Changes',
	settingsShowUntrackedFiles: 'Show untracked files',

	/* Global Settings > Remotes & Fetching */
	settingsSectionRemotesFetching: 'Remotes & Fetching',
	settingsFetchAndPrune: 'Prune when fetching from remotes',
	settingsFetchAndPruneTags: 'Prune tags when fetching from remotes',
	settingsFetchAndPruneTagsInfo: 'Only takes effect when "Prune when fetching from remotes" is enabled, and requires Git 2.17.0 or newer.',
	settingsTrackRemoteTags: 'Track remote tags when fetching',
	settingsShowRemoteBranchesGlobal: 'Show remote branches by default',
	settingsShowRemoteHeads: 'Show remote HEAD symbolic references',

	/* Global Settings > Review Integration */
	settingsSectionReviewIntegration: 'Review Integration',
	settingsPullRequestsEnabled: 'Show the GitHub / GitLab pull request status of the checked-out branch',
	settingsPullRequestsEnabledInfo: 'Uses the GITHUB_TOKEN / GITLAB_TOKEN environment variables for authentication when they are set.',

	settingsSectionConfig: 'Git Graph Configuration',
	settingsSectionLog: 'Log',
	settingsEnableLog: 'Enable Session Log',
	settingsEnableLogInfo: 'While enabled, Git Graph RS records a log (with timings of the load cycle) that can be opened with the "View Session Log" button below. The log starts empty on every editor start.',
	settingsOpenExtensionSettings: 'Open Git Graph Extension Settings',
	settingsOpenLogFile: 'View Session Log',

	/* Settings: the backend section (which engine serves what, on this platform) */
	settingsSectionBackend: 'Backend (this platform)',
	settingsBackendPlatform: 'Platform',
	settingsBackendEngine: 'Rust engine',
	settingsBackendEngineLoaded: 'Loaded (v{0})',
	settingsBackendEngineMissing: 'Not available — everything runs over the git CLI',
	settingsBackendGitCli: 'git CLI',
	settingsBackendGitCliFound: 'Available',
	settingsBackendGitCliMissing: 'Not installed — write operations need it',
	settingsBackendArea: 'Capability',
	settingsBackendProvider: 'Served by',
	settingsBackendProviderRust: 'Rust engine',
	settingsBackendProviderCli: 'git CLI',
	settingsBackendProviderHybrid: 'Hybrid',
	settingsBackendAreaRepoInfo: 'Repository info & refs',
	settingsBackendAreaCommits: 'Commit graph pages',
	settingsBackendAreaDetails: 'Commit, stash & uncommitted details',
	settingsBackendAreaDiffs: 'Comparisons, file contents & diffs',
	settingsBackendAreaOnDemand: 'Search & on-demand reads',
	settingsBackendAreaMetadata: 'Tags, submodules, upstream & remote URLs',
	settingsBackendAreaCounting: 'Commit counting (jump to commit)',
	settingsBackendAreaConfig: 'Repository configuration',
	settingsBackendAreaWrites: 'Write operations (fetch, push, merge, rebase, stash…)',

	settingsExportRepoConfig: 'Export Repository Configuration',
	settingsExportRepoConfigConfirm: 'Exporting the Git Graph Repository Configuration will generate a file that can be committed in this repository. It allows others working in this repository to use the same configuration.',
	settingsYesExport: 'Yes, export',
	settingsExportingRepoConfig: 'Exporting Repository Configuration',
	settingsSavingLanguage: 'Saving Interface Language',
	settingsUnableToSaveLanguage: 'Unable to save the Interface Language',

	/* Pull request status badge */
	prLabel: 'PR',
	prStateOpen: 'Open',
	prStateMerged: 'Merged',
	prStateClosed: 'Closed',
	prStateDraft: 'Draft',
	prStatusTitle: 'Pull Request {0}: {1} (click to open)',
	prOpening: 'Opening Pull Request',

	/* View messages */
	loading: 'Loading ...',
	loadMoreCommits: 'Load More Commits',
	commitNotFound: 'Commit not found in this repository.',
	unableToResumeCodeReview: 'Unable to resume Code Review, it could not be found in the latest {0} commits that were loaded in this repository.',
	unableToLoadRepo: 'Unable to load the Git Graph View for the repository "{0}". It is not currently included in Git Graph.',

	/* Dialog actions: add tag, checkout/create branch, merge, rebase, edit message */
	inputNameLabel: 'Name',
	tagNameInfoSingle: 'The most recent tag in the loaded commits is {0}.',
	tagNameInfoMultiple: 'The most recent tags in the loaded commits are {0}.',
	tagTypeInput: 'Type',
	tagTypeAnnotated: 'Annotated',
	tagTypeLightweight: 'Lightweight',
	messageInput: 'Message',
	optionalPlaceholder: 'Optional',
	tagMessageInfo: 'A message can only be added to an annotated tag.',
	dontPushOption: 'Don\'t push',
	pushToRemoteInput: 'Push to remote',
	pushToRemoteInfo: 'Once this tag has been added, push it to this remote.',
	pushToRemoteRepoInfo: 'Once this tag has been added, push it to the repositories remote.',
	addTagToCommit: 'Add tag to commit <b><i>{0}</i></b>:',
	actionAddTag: 'Add Tag',
	addingTag: 'Adding Tag',
	tagExistsReplace: 'A tag named <b><i>{0}</i></b> already exists, do you want to replace it with this new tag?',
	yesReplaceTag: 'Yes, replace the existing tag',
	noOtherTagName: 'No, choose another tag name',
	checkoutNewBranchPrompt: 'Enter the name of the new branch you would like to create when checking out <b><i>{0}</i></b>:',
	actionCheckoutBranch: 'Checkout Branch',
	branchNameInUse: 'The name <b><i>{0}</i></b> is already used by another branch:',
	chooseAnotherBranchName: 'Choose another branch name',
	checkoutExistingBranch: 'Checkout the existing branch',
	checkoutExistingBranchAndPull: 'Checkout the existing branch & pull changes',
	checkingOutBranch: 'Checking out Branch',
	checkingOutBranchAndPulling: 'Checking out Branch & Pulling Changes',
	createBranchAtCommit: 'Create branch at commit <b><i>{0}</i></b>:',
	checkOutCheckbox: 'Check out',
	actionCreateBranch: 'Create Branch',
	creatingBranch: 'Creating Branch',
	branchExistsReplace: 'A branch named <b><i>{0}</i></b> already exists, do you want to replace it with this new branch?',
	yesReplaceBranch: 'Yes, replace the existing branch',
	noOtherBranchName: 'No, choose another branch name',
	deletingTag: 'Deleting Tag',
	fetchingFromRemotes: 'Fetching from Remote(s)',
	actionOnBranch: 'branch',
	actionOnRemoteTrackingBranch: 'remote-tracking branch',
	actionOnCommit: 'commit',
	currentBranchPlain: 'the current branch',
	currentBranchSuffix: ' (the current branch)',
	mergeConfirm: 'Are you sure you want to merge {0} <b><i>{1}</i></b> into {2}?',
	noFastForwardCheckbox: 'Create a new commit even if fast-forward is possible',
	squashCommitsCheckbox: 'Squash Commits',
	squashMergeInfo: 'Create a single commit on the current branch whose effect is the same as merging this {0}.',
	squashRemoteBranchInfo: 'Create a single commit on the current branch whose effect is the same as merging this remote branch.',
	noCommitCheckbox: 'No Commit',
	noCommitMergeInfo: 'The changes of the merge will be staged but not committed, so that you can review and/or modify the merge result before committing.',
	yesMerge: 'Yes, merge',
	mergingActionOn: 'Merging {0}',
	rebaseConfirm: 'Are you sure you want to rebase {0} on {1} <b><i>{2}</i></b>?',
	interactiveRebaseCheckbox: 'Launch Interactive Rebase in new Terminal',
	ignoreDateCheckbox: 'Ignore Date',
	ignoreDateInfo: 'Only applicable to a non-interactive rebase.',
	yesRebase: 'Yes, rebase',
	launchingInteractiveRebase: 'Launching Interactive Rebase',
	rebasingOnActionOn: 'Rebasing on {0}',
	editCommitMessagePrompt: 'Edit commit message for <b><i>{0}</i></b>:',
	commitMessageInput: 'Commit Message',
	commitMessagePlaceholder: 'Enter the new commit message',
	updateMessageAction: 'Update Message',
	commitMessageEmptyError: 'Commit message cannot be empty.',
	editingCommitMessage: 'Editing Commit Message',

	/* Context menu action dialogs */
	compareBranchTitle: 'Compare Branch',
	compareNoOtherBranches: 'No other local branches to compare with.',
	compareCommitsNotLoaded: 'Could not find the commits for the selected branches in the current view. Try loading more commits.',
	selectBranchToCompare: 'Select branch to compare <b><i>{0}</i></b> with:',
	compareAction: 'Compare',
	renameBranchPrompt: 'Enter the new name for branch <b><i>{0}</i></b>:',
	actionRenameBranch: 'Rename Branch',
	renamingBranch: 'Renaming Branch',
	forceDeleteCheckbox: 'Force Delete',
	deleteOnRemoteCheckbox: 'Delete this branch on the remote',
	deleteOnRemotesCheckbox: 'Delete this branch on the remotes',
	branchOnRemoteInfo: 'This branch is on the remote {0}',
	branchOnRemotesInfo: 'This branch is on the remotes: {0}',
	deleteBranchConfirm: 'Are you sure you want to delete the branch <b><i>{0}</i></b>?',
	yesDelete: 'Yes, delete',
	deletingBranch: 'Deleting Branch',
	setUpstreamCheckbox: 'Set Upstream',
	pushModeInput: 'Push Mode',
	pushModeNormal: 'Normal',
	pushModeForceWithLease: 'Force With Lease',
	pushModeForce: 'Force',
	pushToRemotesInput: 'Push to Remote(s)',
	pushToRemoteOf: ' to the remote <b><i>{0}</i></b>',
	pushBranchConfirm: 'Are you sure you want to push the branch <b><i>{0}</i></b>{1}?',
	yesPush: 'Yes, push',
	pushingBranch: 'Pushing Branch',
	updateBranchConfirm: 'Are you sure you want to update the local branch <b><i>{0}</i></b> with the latest changes from <b><i>{1}</i></b>?',
	forceUpdateCheckbox: 'Force Update',
	forceUpdateInfo: 'Force the local branch to be reset to the remote branch (discard local commits).',
	yesUpdate: 'Yes, update',
	updatingBranch: 'Updating Branch',
	createPullRequestConfirm: 'Are you sure you want to create a Pull Request for branch <b><i>{0}</i></b>?',
	pushBeforePullRequestCheckbox: 'Push branch before creating the Pull Request',
	yesCreatePullRequest: 'Yes, create Pull Request',
	creatingPullRequest: 'Creating Pull Request',
	creatingArchive: 'Creating Archive',
	copyTypeBranchName: 'Branch Name',
	copyTypeCommitHash: 'Commit Hash',
	copyTypeCommitSubject: 'Commit Subject',
	copyTypeStashName: 'Stash Name',
	copyTypeStashHash: 'Stash Hash',
	copyTypeTagName: 'Tag Name',
	copyTypeExternalUrl: 'External URL',
	pinBranch: 'Pin Branch',
	unpinBranch: 'Unpin Branch',
	pinCommit: 'Pin Commit',
	unpinCommit: 'Unpin Commit',
	checkingOutCommit: 'Checking out Commit',
	checkoutCommitConfirm: 'Are you sure you want to checkout commit <b><i>{0}</i></b>? This will result in a \'detached HEAD\' state.',
	alwaysAcceptCheckbox: 'Always Accept',
	yesCheckout: 'Yes, checkout',
	parentHashInput: 'Parent Hash',
	parentHashCherryPickInfo: 'Choose the parent hash on the main branch, to cherry pick the commit relative to.',
	recordOriginCheckbox: 'Record Origin',
	recordOriginInfo: 'Record that this commit was the origin of the cherry pick by appending a line to the original commit message that states "(cherry picked from commit ...)"',
	noCommitCherryPickInfo: 'Cherry picked changes will be staged but not committed, so that you can select and commit specific parts of this commit.',
	cherryPickConfirm: 'Are you sure you want to cherry pick commit <b><i>{0}</i></b>?',
	yesCherryPick: 'Yes, cherry pick',
	cherryPickingCommit: 'Cherry picking Commit',
	revertMergeCommitConfirm: 'Are you sure you want to revert merge commit <b><i>{0}</i></b>? Choose the parent hash on the main branch, to revert the commit relative to:',
	revertCommitConfirm: 'Are you sure you want to revert commit <b><i>{0}</i></b>?',
	yesRevert: 'Yes, revert',
	revertingCommit: 'Reverting Commit',
	resetLastCommitConfirm: 'Are you sure you want to reset the last commit? This will keep all changes from the commit as uncommitted changes.',
	yesResetLastCommit: 'Yes, reset the last commit',
	resettingLastCommit: 'Resetting Last Commit',
	dropCommitConfirm: '<b>Data loss risk</b>: dropping commit <b><i>{0}</i></b> rewrites the current branch\'s history without it. The commit remains recoverable from the local reflog only until git gc prunes it. Are you sure you want to permanently drop it?',
	dropCommitFirstParentNote: '<br/><i>Note: By enabling "Only follow the first parent of commits", some commits may have been hidden from the Git Graph View that could affect the outcome of performing this action.</i>',
	yesDrop: 'Yes, drop',
	droppingCommit: 'Dropping Commit',
	resetToCommitConfirm: 'Are you sure you want to reset {0} to commit <b><i>{1}</i></b>?',
	resetModeSoft: 'Soft - Keep all changes, but reset head',
	resetModeMixed: 'Mixed - Keep working tree, but reset index',
	resetModeHard: 'Hard - Discard all changes',
	yesReset: 'Yes, reset',
	resettingToCommit: 'Resetting to Commit',
	openingExternalDirDiff: 'Opening External Directory Diff',
	deleteRemoteBranchConfirm: '<b>Data loss risk</b>: deleting the remote branch <b><i>{0}</i></b> removes it on the remote; commits only it held there become unreachable to everyone pulling from it. Are you sure you want to delete it?',
	deletingRemoteBranch: 'Deleting Remote Branch',
	fetchIntoLocalConfirm: 'Are you sure you want to fetch the remote branch <b><i>{0}</i></b> into the local branch <b><i>{1}</i></b>?',
	forceFetchCheckbox: 'Force Fetch',
	forceFetchInfo: 'Force the local branch to be reset to this remote branch.',
	yesFetch: 'Yes, fetch',
	fetchingBranch: 'Fetching Branch',
	pullBranchConfirm: 'Are you sure you want to pull the remote branch <b><i>{0}</i></b> into {1}? If a merge is required:',
	yesPull: 'Yes, pull',
	pullingBranch: 'Pulling Branch',
	applyStashConfirm: 'Are you sure you want to apply the stash <b><i>{0}</i></b>?',
	popStashConfirm: 'Are you sure you want to pop the stash <b><i>{0}</i></b>?',
	reinstateIndexCheckbox: 'Reinstate Index',
	reinstateIndexInfo: 'Attempt to reinstate the indexed changes, in addition to the working tree\'s changes.',
	yesApplyStash: 'Yes, apply stash',
	applyingStash: 'Applying Stash',
	branchFromStashPrompt: 'Create a branch from stash <b><i>{0}</i></b> with the name:',
	yesPopStash: 'Yes, pop stash',
	poppingStash: 'Popping Stash',
	dropStashConfirm: '<b>Data loss risk</b>: dropping the stash <b><i>{0}</i></b> deletes its recorded changes, and its reflog goes with it: the stash commit can only be found again with <i>git fsck</i>, until git gc prunes it. Are you sure you want to drop it?',
	droppingStash: 'Dropping Stash',
	retrievingTagDetails: 'Retrieving Tag Details',
	deleteTagConfirm: '<b>Data loss risk</b>: deleting the tag <b><i>{0}</i></b> loses the reference to its commit; recreating it requires knowing the hash. Are you sure you want to delete it?',
	alsoDeleteTagOnRemote: '<br>Do you also want to delete the tag on a remote:',
	dontDeleteOnRemote: 'Don\'t delete on any remote',
	alsoDeleteOnRemoteCheckbox: 'Also delete on remote',
	pushTagToRemoteConfirm: 'Are you sure you want to push the tag <b><i>{0}</i></b> to the remote <b><i>{1}</i></b>?',
	pushTagSelectRemotes: 'Are you sure you want to push the tag <b><i>{0}</i></b>? Select the remote(s) to push the tag to:',
	pushingTag: 'Pushing Tag',
	stashUncommittedConfirm: 'Are you sure you want to stash the <b>uncommitted changes</b>?',
	includeUntrackedCheckbox: 'Include Untracked',
	includeUntrackedInfo: 'Include all untracked files in the stash, and then clean them from the working directory.',
	yesStash: 'Yes, stash',
	stashingUncommitted: 'Stashing uncommitted changes',
	resetUncommittedConfirm: 'Are you sure you want to reset the <b>uncommitted changes</b> to <b>HEAD</b>?',
	resettingUncommitted: 'Resetting uncommitted changes',
	cleanUntrackedConfirm: 'Are you sure you want to clean all untracked files?',
	cleanDirectoriesCheckbox: 'Clean untracked directories',
	yesClean: 'Yes, clean',
	cleaningUntracked: 'Cleaning untracked files',
	selectIssueToView: 'Select which issue you want to view for this branch:',

	/* Action running labels, response errors & special confirmations */
	openingTerminal: 'Opening Terminal',
	pinnedCommitTitle: 'Pinned Commit',
	pinnedCommitNotInLoadedHistory: 'The pinned commit could not be found in this repository\'s loaded history. Clear the branch / path filters and try again.',
	pinnedCommitNotInRepo: 'The pinned commit could not be found in this repository. It may have been rebased away, or excluded by the branch / path filters.',
	pinnedCommitNotInView: 'The pinned commit is not currently in the view. Load more commits or clear the branch / path filters.',
	errLoadRepoInfo: 'Unable to load Repository Info',
	errLoadCommits: 'Unable to load Commits',
	noCommitsInRepo: 'There are no commits in this repository.',
	retryAction: 'Retry',
	unexpectedErrorHandlingMessage: 'An unexpected error occurred while handling a message from the extension: {0}',
	errAddRemote: 'Unable to Add Remote',
	errAddTag: 'Unable to Add Tag',
	errApplyStash: 'Unable to Apply Stash',
	errBranchFromStash: 'Unable to Create Branch from Stash',
	errCheckoutBranch: 'Unable to Checkout Branch',
	errCheckoutBranchPull: 'Unable to Checkout Branch & Pull Changes',
	errCheckoutCommit: 'Unable to Checkout Commit',
	errCherryPick: 'Unable to Cherry Pick Commit',
	errCleanUntracked: 'Unable to Clean Untracked Files',
	errCommitDetails: 'Unable to load Commit Details',
	errCommitComparison: 'Unable to load Commit Comparison',
	errCopyFilePath: 'Unable to Copy File Path to Clipboard',
	errCopyToClipboard: 'Unable to Copy {0} to Clipboard',
	errCreateArchive: 'Unable to Create Archive',
	errCreateBranch: 'Unable to Create Branch',
	errCreatePullRequest: 'Unable to Create Pull Request',
	errDeleteBranch: 'Unable to Delete Branch',
	errDeleteRemote: 'Unable to Delete Remote',
	errDeleteRemoteBranch: 'Unable to Delete Remote Branch',
	errDeleteTag: 'Unable to Delete Tag',
	errDeleteUserDetails: 'Unable to Remove Git User Details',
	errDropCommit: 'Unable to Drop Commit',
	errDropStash: 'Unable to Drop Stash',
	errEditRemote: 'Unable to Save Changes to Remote',
	errEditUserDetails: 'Unable to Save Git User Details',
	errExportRepoConfig: 'Unable to Export Repository Configuration',
	errFetch: 'Unable to Fetch from Remote(s)',
	errFetchIntoLocalBranch: 'Unable to Fetch into Local Branch',
	errMergeActionOn: 'Unable to Merge {0}',
	errRebaseActionOn: 'Unable to Rebase current branch on {0}',
	errOpenExtensionSettings: 'Unable to Open Extension Settings',
	errOpenLogFile: 'Unable to Open the Session Log',
	errOpenExternalDirDiff: 'Unable to Open External Directory Diff',
	errOpenExternalUrl: 'Unable to Open External URL',
	errOpenFile: 'Unable to Open File',
	errOpenTerminal: 'Unable to Open Terminal',
	errPopStash: 'Unable to Pop Stash',
	errPruneRemote: 'Unable to Prune Remote',
	errPullBranch: 'Unable to Pull Branch',
	errPushBranch: 'Unable to Push Branch',
	errPushStash: 'Unable to Stash Uncommitted Changes',
	errPushTag: 'Unable to Push Tag',
	errRenameBranch: 'Unable to Rename Branch',
	errResetFileToRevision: 'Unable to Reset File to Revision',
	errResetToCommit: 'Unable to Reset to Commit',
	errResetLastCommit: 'Unable to Reset Last Commit',
	errRevertCommit: 'Unable to Revert Commit',
	errEditCommitMessage: 'Unable to Edit Commit Message',
		errAmendCommit: 'Unable to Amend Commit',
	errSaveGlobalViewState: 'Unable to save the Global View State',
	errSaveWorkspaceViewState: 'Unable to save the Workspace View State',
	errStartCodeReview: 'Unable to Start Code Review',
	errTagDetails: 'Unable to retrieve Tag Details',
	errUpdateCodeReview: 'Unable to update Code Review',
	errViewDiff: 'Unable to View Diff',
	errViewDiffWithWorkingFile: 'Unable to View Diff with Working File',
	errViewFileAtRevision: 'Unable to View File at Revision',
	errViewScm: 'Unable to open the Source Control View',
	branchNotFullyMerged: '<b>Data loss risk</b>: the branch <b><i>{0}</i></b> is not fully merged. Force deleting it removes the branch\'s own reflog as well: its unmerged commits can only be found again through the local reflogs or <i>git fsck</i>, until git gc prunes them. Would you like to force delete it?',
	yesForceDeleteBranch: 'Yes, force delete branch',
	warnCommitNotOnRemote: 'Warning: Commit is not on Remote ',
	warnCommitNotOnRemotes: 'Warning: Commit is not on Remotes ',
	tagCommitNotOnRemoteSingular: 'The tag <b><i>{0}</i></b> is on a commit that isn\'t on any known branch on the remote {1}.',
	tagCommitNotOnRemotePlural: 'The tag <b><i>{0}</i></b> is on a commit that isn\'t on any known branch on the remotes {1}.',
	proceedPushTagSingular: 'Would you like to proceed to push the tag to the remote {0} anyway?',
	proceedPushTagPlural: 'Would you like to proceed to push the tag to the remotes {0} anyway?',
	alwaysProceedCheckbox: 'Always Proceed',
	proceedToPushAction: 'Proceed to Push',

	/* Commit table, tooltips & misc */
	globPrefix: 'Glob: {0}',
	authorsAll: 'All',
	checkedOutBranchAtCommit: 'The branch "{0}" is currently checked out at this commit.',
	commitCurrentlyCheckedOut: 'This commit is currently checked out.',
	columnGraph: 'Graph',
	columnDescription: 'Description',
	columnDate: 'Date',
	columnAuthor: 'Author',
	columnCommit: 'Commit',
	tagDetailsTitle: 'Tag <b><i>{0}</i></b>',
	tagDetailsObject: '<b>Object: </b>',
	tagDetailsCommit: '<b>Commit: </b>',
	tagDetailsTagger: '<b>Tagger: </b>',
	tagDetailsDate: '<b>Date: </b>',
	signatureDescColon: ':',
	signatureSignedBy: ' Signed by ',
	signatureUnknown: '<Unknown>',
	signatureGpgKeyIdPrefix: ' (GPG Key Id: ',
	signatureGpgKeyIdSuffix: ')',
	signatureStatusValid: 'Valid Signature',
	signatureStatusUnknownValidity: 'Good Signature with Unknown Validity',
	signatureStatusExpired: 'Good Signature that has Expired',
	signatureStatusExpiredKey: 'Good Signature made by an Expired Key',
	signatureStatusRevokedKey: 'Good Signature made by a Revoked Key',
	signatureStatusCouldNotBeChecked: 'Signature could not be checked',
	signatureStatusBad: 'Bad Signature',
	noneValue: 'None',

	/* Commit Details View, file tree & its context menus */
	loadingCommitDetails: 'Loading Commit Details ...',
	loadingUncommittedChanges: 'Loading Uncommitted Changes ...',
	loadingCommitComparison: 'Loading Commit Comparison ...',
	cdvCommitLabel: '<b>Commit: </b>',
	cdvParentsLabel: '<b>Parents: </b>',
	cdvAuthorLabel: '<b>Author: </b>',
	cdvAuthorDateLabel: '<b>Author Date: </b>',
	cdvCommitterLabel: '<b>Committer: </b>',
	cdvDateLabel: '<b>Date: </b>',
	cdvCommitterDateLabel: '<b>Committer Date: </b>',
	displayingUncommitted: 'Displaying all uncommitted changes.',
	displayingChangesFromTo: 'Displaying all changes from <b>{0}</b> to <b>{1}</b>.',
	uncommittedChangesLabel: 'Uncommitted Changes',
	uncommittedChangesRow: 'Uncommitted Changes ({0})',
	fileListViewTitle: 'File List View',
	fileTreeViewTitle: 'File Tree View',
	collapseFoldersTitle: 'Collapse/Expand Folders',
	expandFoldersTitle: 'Expand Folders',
	lastFileViewedTitle: 'Last File Viewed',
	resetFileConfirm: 'Are you sure you want to reset <b><i>{0}</i></b> to it\'s state at commit <b><i>{1}</i></b>? Any uncommitted changes made to this file will be overwritten.',
	yesResetFile: 'Yes, reset file',
	resettingFile: 'Resetting file',
	cdvMenuViewDiff: 'View Diff',
	cdvMenuViewFileAtRevision: 'View File at this Revision',
	cdvMenuViewDiffWithWorkingFile: 'View Diff with Working File',
	cdvMenuOpenFile: 'Open File',
	cdvMenuMarkReviewed: 'Mark as Reviewed',
	cdvMenuMarkNotReviewed: 'Mark as Not Reviewed',
	cdvMenuResetFileToRevision: 'Reset File to this Revision',
	cdvMenuCopyAbsolutePath: 'Copy Absolute File Path to Clipboard',
	cdvMenuCopyRelativePath: 'Copy Relative File Path to Clipboard',
	externalDiffTitle: 'Open External Directory Diff',
	externalDiffWithTool: ' with "{0}"',
	startCodeReviewTitle: 'Start Code Review',
	endCodeReviewTitle: 'End Code Review',
	changeTypeAdded: 'Added',
	changeTypeModified: 'Modified',
	changeTypeDeleted: 'Deleted',
	changeTypeRenamed: 'Renamed',
	changeTypeUntracked: 'Untracked',
	clickToViewDiff: 'Click to View Diff',
	unableToViewDiff: 'Unable to View Diff',
	binaryFileSuffix: ' (this is a binary file)',
	additionSingular: '{0} addition',
	additionPlural: '{0} additions',
	deletionSingular: '{0} deletion',
	deletionPlural: '{0} deletions',
	clickToViewRepo: 'Click to View Repository',

	/* URL & column header context menus, graph tooltip, dropdown & find widget */
	menuOpenUrl: 'Open URL',
	menuFollowInternalLink: 'Follow Internal Link',
	menuCopyUrl: 'Copy URL to Clipboard',
	orderCommitTimestamp: 'Commit Timestamp Order',
	orderAuthorTimestamp: 'Author Timestamp Order',
	orderTopological: 'Topological Order',
	graphTooltipCommit: 'Commit {0}',
	graphTooltipThisCommitIs: 'This commit is ',
	graphTooltipNot: '<b><i>not</i></b> ',
	graphTooltipIncludedInHead: 'included in <span class="graphTooltipRef">HEAD</span>',
	graphTooltipBranches: 'Branches: ',
	graphTooltipTags: 'Tags: ',
	graphTooltipStashes: 'Stashes: ',
	filterDropdownPlaceholder: 'Filter {0}...',
	dropdownNoResults: 'No results found.',
	findZeroLengthMatch: 'Cannot use a regular expression which has zero length matches'
};

type WebviewStrings = typeof STRINGS_EN;

const STRINGS_ZH_CN: WebviewStrings = {
	/* Toolbar & header */
	repoLabel: '仓库：',
	branchesLabel: '分支：',
	authorsLabel: '作者：',
	showRemoteBranchesLabel: '远程',
	showRemoteBranchesTitle: '显示远程分支：在图形中显示远程分支',
	scrollToHeadTitle: '滚动到 HEAD 指向的提交',
	findTitle: '查找',
	filterTitle: '按路径过滤提交',
	filterTitleActive: '按路径过滤提交（当前：{0}）',
	terminalTitle: '为此仓库打开终端',
	settingsTitle: '设置',
	fetchTitle: '从远程仓库拉取',
	fetchAndPruneTitle: '拉取并清理远程引用',
	refreshTitle: '刷新',
	refreshingTitle: '正在刷新',
	pinnedLabel: '已固定：',
	pinnedBranchChipTitle: '仅显示分支 {0}（点击 ✕ 取消固定）',
	pinnedUnpinBranch: '取消固定分支 {0}',
	pinnedCommitChipTitle: '跳转到提交 {0}（点击 ✕ 取消固定）',
	pinnedUnpinCommit: '取消固定提交 {0}',
	pinnedBadgeTitle: '已固定的提交',

	/* Dropdown defaults */
	dropdownRepos: '仓库',
	dropdownBranches: '分支',
	dropdownAuthors: '作者',

	/* Find Widget */
	findPlaceholder: '查找',
	findMatchCase: '区分大小写',
	findUseRegex: '使用正则表达式',
	findPrevMatch: '上一个匹配 (Shift+Enter)',
	findNextMatch: '下一个匹配 (Enter)',
	findOpenCdv: '打开当前匹配项的提交详情视图',
	findClose: '关闭 (Escape)',
	findNoResults: '无结果',
	findPositionOf: '第 {0} 个，共 {1} 个',

	/* Dialogs (common buttons & messages) */
	dialogCancel: '取消',
	dialogClose: '关闭',
	dialogDismiss: '关闭',
	dialogApply: '应用',
	dialogClearFilter: '清除过滤',
	dialogErrorPrefix: '错误：',
	dialogUnableToAction: '无法{0}：输入中包含一个或多个无效字符。',
	filterByPathMessage: '按文件路径过滤提交：',
	filterPathName: '路径',
	filterPathPlaceholder: '例如 src/main.ts、web/（以逗号分隔的多个路径；显示更改了其中任意路径的提交）',

	/* 数据丢失风险警告（执行可能破坏数据的操作前显示） */
	dataLossDialogTitle: '数据丢失风险',
	dataLossContinue: '我已了解风险，继续',
	dataLossMascotCaption: '你的胆子真是肥嘟嘟的！',
	riskResetHard: '硬重置将<b>永久丢弃工作区中所有未提交的更改</b>（包括已暂存和未暂存的更改）。未提交的更改无法恢复。',
	riskCleanUntrackedFiles: '清理操作将<b>永久删除工作目录中所有未跟踪的文件</b>。',
	riskCleanUntrackedDirectories: '清理操作将<b>永久删除工作目录中所有未跟踪的文件和目录</b>。',
	riskCleanUntrackedSuffix: '被删除的文件不会移入回收站，且无法恢复。',
	riskDeleteBranchForce: '强制删除分支 <b>{0}</b> 会使仅在该分支上可达的提交变为不可达，Git 可能将其永久清除。',
	riskDeleteBranchRemote: '在 {0} 上删除该分支，会使仓库的所有协作者失去此分支。',
	riskDeleteRemoteBranch: '删除远程分支 <b>{0}</b> 会使仓库的所有协作者失去此分支，仅在该分支上可达的提交可能被永久丢失。',
	riskPushForce: '强制推送将<b>覆盖远程分支 {0}</b>。远程上存在而本地没有的提交可能被永久丢失。',
	riskPushForceWithLease: '强制推送（带 lease）在远程分支未变化时会<b>覆盖远程分支 {0}</b>。远程上存在而本地没有的提交可能被永久丢失。',
	riskFetchIntoLocalBranchForce: '强制更新将<b>把本地分支 {0} 重置为远程分支</b>，丢弃本地所有不在远程上的提交。',
	riskDropCommit: '丢弃此提交会在不包含它的情况下重写当前分支的历史。被丢弃的提交只能通过 reflog 找回。',
	riskDropStash: '丢弃此储藏将<b>永久移除其中保存的更改</b>。如果这些更改未在其他地方应用，将无法恢复。',
	riskResetFile: '重置 <b>{0}</b> 将<b>永久丢弃该文件在工作区中所有未提交的更改</b>。',

	/* Context menus - commits */
	menuCheckoutBranch: '检出分支',
	menuCompareWith: '比较...',
	menuCheckout: '检出',
	menuAddTag: '添加标签',
	menuCreateBranch: '创建分支',
	menuCherryPick: '拣选(Cherry Pick)',
	menuRevert: '还原(Revert)',
	menuDrop: '丢弃(Drop)',
	menuMergeIntoCurrentBranch: '合并到当前分支',
	menuRebaseOnBranch: '将当前分支变基到该分支',
	menuRebaseOnCommit: '将当前分支变基到该提交',
	menuResetToCommit: '将当前分支重置到该提交',
	menuResetLastCommitSoft: '重置上一次提交(软重置)',
	menuEditMessage: '编辑提交信息',
	menuPushBranch: '推送分支',
	menuPullBranch: '拉取分支',
	menuPullIntoCurrentBranch: '拉取到当前分支',
	menuCopyCommitHash: '复制提交哈希到剪贴板',
	menuCopyCommitSubject: '复制提交主题到剪贴板',
	menuSelectForCompare: '选择以比较',
	menuCompareWithSelected: '与选定的提交比较',
	menuDiffWithWorkingTree: '与工作区比较差异',

	/* Context menus - branches & remotes */
	menuRenameBranch: '重命名分支',
	menuDeleteBranch: '删除分支',
	menuDeleteRemoteBranch: '删除远程分支',
	menuFetchIntoLocalBranch: '拉取(Fetch)到本地分支',
	menuCreatePullRequest: '创建拉取请求',
	menuCreateArchive: '创建归档',
	menuSelectInBranchesDropdown: '在分支下拉列表中选中',
	menuUnselectInBranchesDropdown: '在分支下拉列表中取消选中',
	menuCopyBranchName: '复制分支名称到剪贴板',
	menuViewIssue: '查看 Issue',

	/* Context menus - stashes, tags & uncommitted changes */
	menuApplyStash: '应用贮藏(Apply Stash)',
	menuCreateBranchFromStash: '从贮藏创建分支',
	menuPopStash: '弹出贮藏(Pop Stash)',
	menuDropStash: '丢弃贮藏(Drop Stash)',
	menuCopyStashName: '复制贮藏名称到剪贴板',
	menuCopyStashHash: '复制贮藏哈希到剪贴板',
	menuViewDetails: '查看详情',
	menuDeleteTag: '删除标签',
	menuPushTag: '推送标签',
	menuCopyTagName: '复制标签名称到剪贴板',
	menuStashUncommitted: '贮藏未提交的更改',
	menuResetUncommitted: '重置未提交的更改',
	menuCleanUntracked: '清理未跟踪文件',
	menuOpenSourceControlView: '打开源代码管理视图',


	/* Settings Widget */
	settingsSectionGeneral: '常规',
	settingsNameLabel: '名称：',
	settingsNameDefault: '（文件系统默认名称）',
	settingsEditNameTitle: '编辑名称',
	settingsDeleteNameTitle: '删除名称',
	settingsInitialBranchesLabel: '初始分支：',
	settingsCheckedOut: '已检出',
	settingsShowAll: '显示全部',
	settingsLocal: '本地',
	settingsGlobal: '全局',
	settingsEditInitialBranchesTitle: '编辑初始分支',
	settingsClearInitialBranchesTitle: '清除初始分支',
	settingsShowStashes: '显示贮藏',
	settingsShowTags: '显示标签',
	settingsIncludeReflogs: '包含仅被 reflog 提及的提交',
	settingsIncludeReflogsInfo: '仅在显示所有分支时生效。',
	settingsOnlyFirstParent: '仅跟随提交的第一个父提交',
	settingsOnlyFirstParentInfo: '发现要加载的提交时，仅跟随第一个父提交，而不跟随提交的所有父提交。',
	settingsInterfaceLanguageLabel: '界面语言：',
	settingsLanguageAuto: '自动（跟随 VS Code）',
	settingsLanguageEnglish: 'English',
	settingsLanguageChinese: '\u4e2d\u6587\uff08\u7b80\u4f53\uff09',
	settingsNameDialogMessage: '为此仓库指定名称：',
	settingsNameInput: '名称',
	settingsNameDialogSave: '保存名称',
	settingsDeleteNameConfirm: '确定要删除为此仓库手动配置的名称 <b><i>{0}</i></b>，并使用文件系统的默认名称 <b><i>{1}</i></b> 吗？',
	settingsYesDelete: '是，删除',
	settingsInitialBranchesDialogHeader: '<b>配置初始分支</b>',
	settingsInitialBranchesDialogText: '配置在 Git Graph 视图中加载此仓库时初始显示的分支。',
	settingsInitialBranchesDialogNote: '注意：当禁用“已检出分支”且未选择任何“特定分支”时，将显示所有分支。',
	settingsInitialBranchesCheckedOutInput: '已检出分支',
	settingsInitialBranchesSpecificInput: '特定分支',
	settingsSaveConfiguration: '保存配置',
	settingsClearInitialBranchesConfirm: '确定要清除在 Git Graph 视图中加载此仓库时初始显示的分支吗？',
	settingsYesClear: '是，清除',
	settingsNotSet: '未设置',

	settingsSectionUserDetails: '用户信息',
	settingsUserNameLabel: '用户名：',
	settingsUserEmailLabel: '用户邮箱：',
	settingsEdit: '编辑',
	settingsRemove: '移除',
	settingsUserDetailsIntro: '用户信息（例如姓名和邮箱）由 Git 用来记录提交对象的作者和提交者。',
	settingsAddUserDetails: '添加用户信息',
	settingsUserDetailsDialogMessage: '设置由 Git 用来记录提交对象作者和提交者的用户名和邮箱：',
	settingsUserNameInput: '用户名',
	settingsUserEmailInput: '用户邮箱',
	settingsUseGlobally: '全局使用',
	settingsUseGloballyInfo: '在所有 Git 仓库中全局使用该“用户名”和“用户邮箱”（可以按仓库覆盖）。',
	settingsSetUserDetails: '设置用户信息',
	settingsSettingUserDetails: '正在设置用户信息',
	settingsGlobally: '全局',
	settingsLocally: '本地',
	settingsRemoveUserDetailsConfirm: '确定要移除<b>{0}配置的</b>用户名和邮箱吗？它们由 Git 用来记录提交对象的作者和提交者。',
	settingsYesRemove: '是，移除',
	settingsRemovingUserDetails: '正在移除用户信息',

	settingsSectionRemotes: '远程配置',
	settingsRemote: '远程',
	settingsUrl: 'URL',
	settingsType: '类型',
	settingsAction: '操作',
	settingsFetch: '拉取',
	settingsPush: '推送',
	settingsShowRemoteTitle: '点击显示此远程的分支。',
	settingsHideRemoteTitle: '点击隐藏此远程的分支。',
	settingsFetchFromRemoteTitle: '从远程拉取',
	settingsPruneRemoteTitle: '清理远程',
	settingsEditRemoteTitle: '编辑远程',
	settingsDeleteRemoteTitle: '删除远程',
	settingsNoRemotes: '此仓库未配置任何远程。',
	settingsAddRemote: '添加远程',
	settingsAddRemoteDialogMessage: '为此仓库添加新的远程：',
	settingsFetchUrlInput: '拉取 URL',
	settingsPushUrlInput: '推送 URL',
	settingsPushUrlPlaceholder: '留空则使用拉取 URL',
	settingsFetchImmediately: '立即拉取',
	settingsAddingRemote: '正在添加远程',
	settingsEditRemoteDialogMessage: '编辑远程 <b><i>{0}</i></b>：',
	settingsSaveChanges: '保存更改',
	settingsSavingRemoteChanges: '正在保存远程更改',
	settingsDeleteRemoteConfirm: '确定要删除远程 <b><i>{0}</i></b> 吗？',
	settingsDeletingRemote: '正在删除远程',
	settingsFetchRemoteConfirm: '确定要从远程 <b><i>{0}</i></b> 拉取吗？',
	settingsPrune: '清理',
	settingsPruneInfo: '拉取前，移除远程上已不存在的远程跟踪引用。',
	settingsPruneTags: '清理标签',
	settingsPruneTagsInfo: '拉取前，移除远程上已不存在的本地标签。需要 Git >= 2.17.0，且启用“清理”。',
	settingsYesFetch: '是，拉取',
	settingsFetchingFromRemote: '正在从远程拉取',
	settingsPruneRemoteConfirm: '确定要清理远程 <b><i>{0}</i></b> 上已不存在的远程跟踪引用吗？',
	settingsYesPrune: '是，清理',
	settingsPruningRemote: '正在清理远程',

	settingsSave: '保存',
	settingsBack: '上一步',
	settingsGoBack: '返回',
	settingsYesHide: '是，隐藏',

	settingsSectionIssueLinking: 'Issue 关联',
	settingsIssueRegexLabel: 'Issue 正则：',
	settingsIssueUrlLabel: 'Issue URL：',
	settingsIssueLinkingIntro: 'Issue 关联将提交和标签信息中的 issue 编号转换为超链接，在其跟踪系统中打开该 issue。如果分支名包含 issue 编号，可通过分支的上下文菜单查看该 issue。',
	settingsAddIssueLinking: '添加 Issue 关联',
	settingsEditIssueLinkingHeader: '<b>编辑此仓库的 Issue 关联</b>',
	settingsAddIssueLinkingHeader: '<b>为此仓库添加 Issue 关联</b>',
	settingsIssueExampleText: '以下示例将提交信息中的 <b>#123</b> 链接到 <b>https://github.com/your-org/your-repo/issues/123</b>：',
	settingsIssueRegexDetected: '预填的 Issue 正则是在此仓库的提交信息中检测到的。如有必要请检查和/或更正。',
	settingsIssueRegexInput: 'Issue 正则',
	settingsIssueRegexInfo: '匹配 issue 编号的正则表达式，包含一个或多个捕获组 ( )，将被替换到“Issue URL”中。',
	settingsIssueUrlInput: 'Issue URL',
	settingsIssueUrlInfo: 'issue 在您的 issue 跟踪系统中的 URL，其中的占位符（$1、$2 等）对应“Issue 正则”中捕获 ( ) 的分组。',
	settingsUseGloballyIssueInfo: '默认在所有仓库中使用该“Issue 正则”和“Issue URL”（可以按仓库覆盖）。注意：仅当相同的 Issue 关联适用于您的大多数仓库时（例如使用 JIRA 或 Pivotal Tracker 时），“全局使用”才合适。',
	settingsInvalidIssueRegex: 'Issue 正则无效',
	settingsIssueRegexNoGroup: '正则表达式不包含捕获组 ( )。',
	settingsInvalidIssueUrl: 'Issue URL 无效',
	settingsIssueUrlNoPlaceholders: 'Issue URL 不包含任何占位符（$1、$2 等）用于 Issue 正则中捕获的 issue 编号组成部分。',
	settingsRemoveConfirmPrefix: '确定要移除',
	settingsRemoveIssueLinkingLocal: '<b>本地配置的</b>',
	settingsRemoveIssueLinkingFromRepo: '此仓库的 Issue 关联',
	settingsRemoveIssueLinkingGlobal: 'Git Graph 中<b>全局配置的</b> Issue 关联',

	settingsSectionPullRequest: '拉取请求创建',
	settingsProviderLabel: '提供商：',
	settingsSourceRepoLabel: '源仓库：',
	settingsDestinationRepoLabel: '目标仓库：',
	settingsDestinationBranchLabel: '目标分支：',
	settingsPrIntro: '拉取请求创建可直接从分支的上下文菜单自动打开并预填拉取请求表单。',
	settingsConfigurePrIntegration: '配置“拉取请求创建”集成',
	settingsUnableToConfigurePr: '无法配置“拉取请求创建”集成',
	settingsPrNeedsRemote: '配置“拉取请求创建”集成要求仓库至少有一个远程。当前仓库没有任何远程。',
	settingsPrDialog1Header: '配置“拉取请求创建”集成（步骤 1/2）',
	settingsPrDialog2Header: '配置“拉取请求创建”集成（步骤 2/2）',
	settingsPrProviderInput: '提供商',
	settingsPrProviderInfo: '除内置的公共托管拉取请求提供商外，还可以使用扩展设置 “git-graph-rs.customPullRequestProviders” 配置自定义提供商（例如用于私有部署的拉取请求提供商）。',
	settingsPrSourceRemoteInput: '源远程',
	settingsPrSourceRemoteInfo: '对应拉取请求来源的远程。',
	settingsPrDestRemoteInput: '目标远程',
	settingsPrDestRemoteInfo: '对应拉取请求目标（去向）的远程。',
	settingsNotARemote: '非远程',
	settingsNext: '下一步',
	settingsHostRootUrlInput: '主机根 URL',
	settingsHostRootUrlInfo: '拉取请求提供商的主机根 URL（例如 https://github.com）。',
	settingsSourceOwnerInput: '源所有者',
	settingsSourceOwnerInfo: '作为拉取请求来源的仓库的所有者。',
	settingsSourceRepoInput: '源仓库',
	settingsSourceRepoInfo: '作为拉取请求来源的仓库的名称。',
	settingsDestOwnerInput: '目标所有者',
	settingsDestOwnerInfo: '作为拉取请求目标（去向）的仓库的所有者。',
	settingsDestRepoInput: '目标仓库',
	settingsDestRepoInfo: '作为拉取请求目标（去向）的仓库的名称。',
	settingsDestProjectIdInput: '目标项目 ID',
	settingsDestProjectIdInfo: '拉取请求目标（去向）的 GitLab 项目 ID。留空则使用 GitLab 中配置的默认目标。',
	settingsDestBranchInput: '目标分支',
	settingsDestBranchInfo: '作为拉取请求目标（去向）的分支的名称。',
	settingsRemovePrConfirm: '确定要移除已配置的“拉取请求创建”集成吗？',

	/* Repository Settings > Gerrit */
	settingsSectionGerrit: 'Gerrit 变更引用',
	settingsGerritFetchRefs: '获取 Gerrit 变更引用 (refs/changes/*)',
	settingsGerritFetchRefsInfo: '将最近的 Gerrit 变更获取到 refs/remotes/<gerrit.remote>/changes/（每个变更的最新补丁集和 NoteDb meta 引用，数量上限可在下方设置，或通过 git-graph-rs.gerrit.fetchLimit 设置全局默认）。属于某个变更的提交会显示变更徽章——点击徽章可查看评审信息。取消勾选会删除本地已获取的变更引用并停止获取。',
	settingsGerritStatusFilterLabel: '显示以下状态的变更：',
	settingsGerritStatusOpen: '开放',
	settingsGerritStatusMerged: '已合并',
	settingsGerritStatusAbandoned: '已废弃',
	settingsGerritStatusWip: '进行中 (WIP)',
	settingsGerritDisableConfirm: '确定要禁用 Gerrit 变更引用的获取吗？<br><span class="messageContent">本地已获取的全部变更引用（refs/remotes/&lt;gerrit.remote&gt;/changes/*）将被删除。已下载的提交会保留在对象库中，直到 Git 垃圾回收。</span>',
	settingsGerritDisableAction: '是，禁用',
	settingsGerritEnabling: '正在启用 Gerrit 变更引用获取',
	settingsGerritClearing: '正在删除 Gerrit 变更引用',
	errGerritSetFetchRefs: '无法更改 Gerrit 变更引用获取设置',

	/* Gerrit 变更徽章与评审对话框 */
	gerritBadgeTitle: 'Gerrit 变更 #{0}/{1} - 点击查看评审详情',
	gerritChangeHeader: 'Gerrit 变更 #{0}',
	gerritPatchSetLabel: '补丁集 {0}',
	gerritOwnerLabel: '所有者：{0}',
	gerritOpenInGerrit: '在 Gerrit 中打开',
	gerritCodeReviewLabel: 'Code-Review',
	gerritVerifiedLabel: 'Verified',
	gerritStatusOpen: '开放（等待评审）',
	gerritStatusMerged: '已合并',
	gerritStatusAbandoned: '已废弃',
	gerritStatusWip: '进行中',
	gerritReviewDialogTitle: 'Gerrit 评审',
	gerritNoReviewInfo: '该提交没有可用的 Gerrit 评审信息。只有其变更的 NoteDb meta 引用被解析过的提交才有评审信息。',
	gerritToggleNoteDb: '点击切换显示该事件的完整 NoteDb 记录',
	gerritEventsHint: '点击事件可显示其完整的 NoteDb 记录（补丁集、提交哈希、标签和状态页脚）。',
	gerritTimelineLabel: '评审记录',
	gerritEventsPending: '评审记录仍在加载中 …',
	settingsGerritFetchLimitLabel: '获取上限',
	settingsGerritFetchLimitInfo: '将最近多少个 Gerrit 变更获取到 refs/remotes/<gerrit.remote>/changes/ 下（每个变更的最新补丁集与 NoteDb meta 引用）。范围 1–10000；输入留空时跟随 git-graph-rs.gerrit.fetchLimit 设置。',
	settingsGerritFetchLimitEditTitle: '编辑 Gerrit 获取上限',
	settingsGerritFetchLimitInput: '获取的变更数量',
	settingsGerritFetchLimitPlaceholder: '留空 = 全局设置',
	settingsGerritFetchLimitGlobal: '全局设置（{0}）',

	/* Settings columns */
	settingsColumnRepo: '仓库设置',
	settingsColumnRepoHint: '仅应用于当前视图中打开的仓库',
	settingsColumnGlobal: '全局设置',
	settingsColumnGlobalHint: '应用于所有仓库（保存到 VS Code 用户设置）',
	settingsSavingSetting: '正在保存设置',
	settingsUnableToSaveSetting: '无法保存设置',

	/* Global Settings > Graph & Display */
	settingsSectionGraphDisplay: '图形与显示',
	settingsGraphStyleLabel: '图形样式：',
	settingsGraphStyleRounded: '圆角',
	settingsGraphStyleAngular: '直角',
	settingsGraphRowHeightLabel: '行高：',
	settingsGraphFontSizeLabel: '字号：',
	settingsDateTypeLabel: '显示日期：',
	settingsDateTypeAuthor: '作者日期',
	settingsDateTypeCommit: '提交日期',
	settingsDateFormatLabel: '日期格式：',
	settingsDateFormatDateAndTime: '日期与时间',
	settingsDateFormatDateOnly: '仅日期',
	settingsDateFormatIsoDateAndTime: 'ISO 日期与时间',
	settingsDateFormatIsoDateOnly: 'ISO 仅日期',
	settingsDateFormatRelative: '相对时间',
	settingsCombineBranchLabels: '合并本地与远程分支标签',
	settingsStickyHeader: '滚动时固定表头',
	settingsRenderMarkdown: '在提交信息中渲染 Markdown',

	/* Global Settings > Commit Loading */
	settingsSectionCommitLoading: '提交加载',
	settingsInitialLoadLabel: '首次加载：',
	settingsLoadMoreLabel: '每次加载更多：',
	settingsCommitsUnit: '条提交',
	settingsLoadMoreAutomatically: '自动加载更多提交',
	settingsCommitOrderLabel: '提交排序：',
	settingsCommitOrderDate: '提交日期',
	settingsCommitOrderAuthorDate: '作者日期',
	settingsCommitOrderTopo: '拓扑顺序',
	settingsFetchAvatars: '获取提交作者头像',
	settingsShowUncommittedChanges: '显示未提交的更改',
	settingsShowUntrackedFiles: '显示未跟踪的文件',

	/* Global Settings > Remotes & Fetching */
	settingsSectionRemotesFetching: '远程与抓取',
	settingsFetchAndPrune: '抓取时清理失效的远程分支',
	settingsFetchAndPruneTags: '抓取时清理失效的标签',
	settingsFetchAndPruneTagsInfo: '仅在启用“抓取时清理失效的远程分支”时生效，且需要 Git 2.17.0 或更高版本。',
	settingsTrackRemoteTags: '抓取时跟踪远程标签',
	settingsShowRemoteBranchesGlobal: '默认显示远程分支',
	settingsShowRemoteHeads: '显示远程 HEAD 符号引用',

	/* Global Settings > Review Integration */
	settingsSectionReviewIntegration: 'Review 集成',
	settingsPullRequestsEnabled: '显示当前分支的 GitHub / GitLab 拉取请求状态',
	settingsPullRequestsEnabledInfo: '设置了 GITHUB_TOKEN / GITLAB_TOKEN 环境变量时将使用其进行认证。',

	settingsSectionConfig: 'Git Graph 配置',
	settingsSectionLog: '日志',
	settingsEnableLog: '启用会话日志',
	settingsEnableLogInfo: '启用后 Git Graph RS 会记录日志（含加载各环节耗时），可通过下方"查看会话日志"按钮打开。日志在每次编辑器启动时清空。',
	settingsOpenExtensionSettings: '打开 Git Graph 扩展设置',
	settingsOpenLogFile: '查看会话日志',

	/* Settings: the backend section (which engine serves what, on this platform) */
	settingsSectionBackend: '后端（当前平台）',
	settingsBackendPlatform: '平台',
	settingsBackendEngine: 'Rust 引擎',
	settingsBackendEngineLoaded: '已加载（v{0}）',
	settingsBackendEngineMissing: '不可用 —— 全部功能通过 git 命令行运行',
	settingsBackendGitCli: 'git 命令行',
	settingsBackendGitCliFound: '可用',
	settingsBackendGitCliMissing: '未安装 —— 写入类操作需要它',
	settingsBackendArea: '功能',
	settingsBackendProvider: '提供服务',
	settingsBackendProviderRust: 'Rust 引擎',
	settingsBackendProviderCli: 'git 命令行',
	settingsBackendProviderHybrid: '混合',
	settingsBackendAreaRepoInfo: '仓库信息与引用',
	settingsBackendAreaCommits: '提交图分页',
	settingsBackendAreaDetails: '提交、贮藏与未提交详情',
	settingsBackendAreaDiffs: '比较、文件内容与差异',
	settingsBackendAreaOnDemand: '搜索与按需读取',
	settingsBackendAreaMetadata: '标签、子模块、上游与远程地址',
	settingsBackendAreaCounting: '提交计数（跳转定位）',
	settingsBackendAreaConfig: '仓库配置读取',
	settingsBackendAreaWrites: '写操作（fetch、push、merge、rebase、stash……）',

	settingsExportRepoConfig: '导出仓库配置',
	settingsExportRepoConfigConfirm: '导出 Git Graph 仓库配置会生成一个可以提交到此仓库的文件，使在此仓库中工作的其他人可以使用相同的配置。',
	settingsYesExport: '是，导出',
	settingsExportingRepoConfig: '正在导出仓库配置',
	settingsSavingLanguage: '正在保存界面语言',
	settingsUnableToSaveLanguage: '无法保存界面语言',

	/* Pull request status badge */
	prLabel: 'PR',
	prStateOpen: '打开',
	prStateMerged: '已合并',
	prStateClosed: '已关闭',
	prStateDraft: '草稿',
	prStatusTitle: '拉取请求 {0}：{1}（点击打开）',
	prOpening: '正在打开拉取请求',

	/* View messages */
	loading: '正在加载...',
	loadMoreCommits: '加载更多提交',
	commitNotFound: '在该仓库中找不到该提交。',
	unableToResumeCodeReview: '无法恢复代码评审：在该仓库最近加载的 {0} 个提交中找不到它。',
	unableToLoadRepo: '无法为仓库“{0}”加载 Git Graph 视图。它当前未包含在 Git Graph 中。',

	/* 对话框操作：添加标签、检出/创建分支、合并、变基、编辑提交信息 */
	inputNameLabel: '名称',
	tagNameInfoSingle: '已加载提交中最近的标签是 {0}。',
	tagNameInfoMultiple: '已加载提交中最近的标签有 {0}。',
	tagTypeInput: '类型',
	tagTypeAnnotated: '附注(Annotated)',
	tagTypeLightweight: '轻量(Lightweight)',
	messageInput: '信息',
	optionalPlaceholder: '可选',
	tagMessageInfo: '只有附注标签才能添加信息。',
	dontPushOption: '不推送',
	pushToRemoteInput: '推送到远程',
	pushToRemoteInfo: '添加此标签后，将其推送到该远程。',
	pushToRemoteRepoInfo: '添加此标签后，将其推送到该仓库的远程。',
	addTagToCommit: '为提交 <b><i>{0}</i></b> 添加标签：',
	actionAddTag: '添加标签',
	addingTag: '正在添加标签',
	tagExistsReplace: '名为 <b><i>{0}</i></b> 的标签已存在，是否用新标签替换它？',
	yesReplaceTag: '是，替换现有标签',
	noOtherTagName: '否，选择其他标签名',
	checkoutNewBranchPrompt: '输入检出 <b><i>{0}</i></b> 时要创建的新分支的名称：',
	actionCheckoutBranch: '检出分支',
	branchNameInUse: '名称 <b><i>{0}</i></b> 已被另一个分支使用：',
	chooseAnotherBranchName: '选择其他分支名称',
	checkoutExistingBranch: '检出已存在的分支',
	checkoutExistingBranchAndPull: '检出已存在的分支并拉取更改',
	checkingOutBranch: '正在检出分支',
	checkingOutBranchAndPulling: '正在检出分支并拉取更改',
	createBranchAtCommit: '在提交 <b><i>{0}</i></b> 处创建分支：',
	checkOutCheckbox: '检出',
	actionCreateBranch: '创建分支',
	creatingBranch: '正在创建分支',
	branchExistsReplace: '名为 <b><i>{0}</i></b> 的分支已存在，是否用新分支替换它？',
	yesReplaceBranch: '是，替换现有分支',
	noOtherBranchName: '否，选择其他分支名称',
	deletingTag: '正在删除标签',
	fetchingFromRemotes: '正在从远程拉取',
	actionOnBranch: '分支',
	actionOnRemoteTrackingBranch: '远程跟踪分支',
	actionOnCommit: '提交',
	currentBranchPlain: '当前分支',
	currentBranchSuffix: '（当前分支）',
	mergeConfirm: '确定要将{0} <b><i>{1}</i></b> 合并到 {2} 吗？',
	noFastForwardCheckbox: '即使可以快进也创建新提交',
	squashCommitsCheckbox: '压缩提交(Squash)',
	squashMergeInfo: '在当前分支上创建单个提交，其效果与合并此{0}相同。',
	squashRemoteBranchInfo: '在当前分支上创建单个提交，其效果与合并此远程分支相同。',
	noCommitCheckbox: '不提交',
	noCommitMergeInfo: '合并的更改将被暂存但不提交，以便在提交前检查和/或修改合并结果。',
	yesMerge: '是，合并',
	mergingActionOn: '正在合并{0}',
	rebaseConfirm: '确定要将 {0} 变基到{1} <b><i>{2}</i></b> 上吗？',
	interactiveRebaseCheckbox: '在新终端中启动交互式变基',
	ignoreDateCheckbox: '忽略日期',
	ignoreDateInfo: '仅适用于非交互式变基。',
	yesRebase: '是，变基',
	launchingInteractiveRebase: '正在启动交互式变基',
	rebasingOnActionOn: '正在变基到{0}',
	editCommitMessagePrompt: '编辑提交 <b><i>{0}</i></b> 的提交信息：',
	commitMessageInput: '提交信息',
	commitMessagePlaceholder: '输入新的提交信息',
	updateMessageAction: '更新信息',
	commitMessageEmptyError: '提交信息不能为空。',
	editingCommitMessage: '正在编辑提交信息',

	/* 右键菜单操作对话框 */
	compareBranchTitle: '比较分支',
	compareNoOtherBranches: '没有其他本地分支可供比较。',
	compareCommitsNotLoaded: '在当前视图中找不到所选分支的提交。请尝试加载更多提交。',
	selectBranchToCompare: '选择要与 <b><i>{0}</i></b> 比较的分支：',
	compareAction: '比较',
	renameBranchPrompt: '输入分支 <b><i>{0}</i></b> 的新名称：',
	actionRenameBranch: '重命名分支',
	renamingBranch: '正在重命名分支',
	forceDeleteCheckbox: '强制删除',
	deleteOnRemoteCheckbox: '删除该远程上的此分支',
	deleteOnRemotesCheckbox: '删除远程上的此分支',
	branchOnRemoteInfo: '此分支位于远程 {0} 上',
	branchOnRemotesInfo: '此分支位于以下远程上：{0}',
	deleteBranchConfirm: '确定要删除分支 <b><i>{0}</i></b> 吗？',
	yesDelete: '是，删除',
	deletingBranch: '正在删除分支',
	setUpstreamCheckbox: '设置上游',
	pushModeInput: '推送模式',
	pushModeNormal: '普通',
	pushModeForceWithLease: '强制（lease）',
	pushModeForce: '强制',
	pushToRemotesInput: '推送到远程',
	pushToRemoteOf: ' 到远程 <b><i>{0}</i></b>',
	pushBranchConfirm: '确定要推送分支 <b><i>{0}</i></b>{1} 吗？',
	yesPush: '是，推送',
	pushingBranch: '正在推送分支',
	updateBranchConfirm: '确定要用 <b><i>{1}</i></b> 的最新更改更新本地分支 <b><i>{0}</i></b> 吗？',
	forceUpdateCheckbox: '强制更新',
	forceUpdateInfo: '强制将本地分支重置为远程分支（丢弃本地提交）。',
	yesUpdate: '是，更新',
	updatingBranch: '正在更新分支',
	createPullRequestConfirm: '确定要为分支 <b><i>{0}</i></b> 创建拉取请求吗？',
	pushBeforePullRequestCheckbox: '创建拉取请求前先推送分支',
	yesCreatePullRequest: '是，创建拉取请求',
	creatingPullRequest: '正在创建拉取请求',
	creatingArchive: '正在创建归档',
	copyTypeBranchName: '分支名称',
	copyTypeCommitHash: '提交哈希',
	copyTypeCommitSubject: '提交主题',
	copyTypeStashName: '贮藏名称',
	copyTypeStashHash: '贮藏哈希',
	copyTypeTagName: '标签名称',
	copyTypeExternalUrl: '外部 URL',
	pinBranch: '固定分支',
	unpinBranch: '取消固定分支',
	pinCommit: '固定提交',
	unpinCommit: '取消固定提交',
	checkingOutCommit: '正在检出提交',
	checkoutCommitConfirm: '确定要检出提交 <b><i>{0}</i></b> 吗？这将导致“分离头指针（detached HEAD）”状态。',
	alwaysAcceptCheckbox: '总是接受',
	yesCheckout: '是，检出',
	parentHashInput: '父提交哈希',
	parentHashCherryPickInfo: '选择主分支上的父提交哈希，作为拣选该提交的相对基准。',
	recordOriginCheckbox: '记录来源',
	recordOriginInfo: '在原提交信息末尾追加“(cherry picked from commit ...)”一行，记录该提交是此次拣选的来源',
	noCommitCherryPickInfo: '拣选的更改将被暂存但不提交，以便选择并提交该提交的特定部分。',
	cherryPickConfirm: '确定要拣选提交 <b><i>{0}</i></b> 吗？',
	yesCherryPick: '是，拣选',
	cherryPickingCommit: '正在拣选提交',
	revertMergeCommitConfirm: '确定要还原合并提交 <b><i>{0}</i></b> 吗？请选择主分支上的父提交哈希，作为还原该提交的相对基准：',
	revertCommitConfirm: '确定要还原提交 <b><i>{0}</i></b> 吗？',
	yesRevert: '是，还原',
	revertingCommit: '正在还原提交',
	resetLastCommitConfirm: '确定要重置上一次提交吗？该提交的所有更改将保留为未提交的更改。',
	yesResetLastCommit: '是，重置上一次提交',
	resettingLastCommit: '正在重置上一次提交',
	dropCommitConfirm: '<b>数据丢失风险</b>：丢弃提交 <b><i>{0}</i></b> 会在不包含它的情况下重写当前分支的历史。该提交在被 git gc 清理前仍可从本机 reflog 找回。确定要永久丢弃吗？',
	dropCommitFirstParentNote: '<br/><i>注意：启用“仅跟随提交的第一个父提交”后，部分提交可能已被隐藏在 Git Graph 视图之外，它们可能影响此操作的结果。</i>',
	yesDrop: '是，丢弃',
	droppingCommit: '正在丢弃提交',
	resetToCommitConfirm: '确定要将 {0} 重置到提交 <b><i>{1}</i></b> 吗？',
	resetModeSoft: '软重置 - 保留所有更改，仅重置 HEAD',
	resetModeMixed: '混合重置 - 保留工作区，但重置索引',
	resetModeHard: '硬重置 - 丢弃所有更改',
	yesReset: '是，重置',
	resettingToCommit: '正在重置到提交',
	openingExternalDirDiff: '正在打开外部目录比较',
	deleteRemoteBranchConfirm: '<b>数据丢失风险</b>：删除远程分支 <b><i>{0}</i></b> 会将其从远端移除，仅存在于该分支上的提交对所有从这里拉取的人都将不可达。确定要删除吗？',
	deletingRemoteBranch: '正在删除远程分支',
	fetchIntoLocalConfirm: '确定要将远程分支 <b><i>{0}</i></b> 拉取(Fetch)到本地分支 <b><i>{1}</i></b> 吗？',
	forceFetchCheckbox: '强制拉取',
	forceFetchInfo: '强制将本地分支重置为该远程分支。',
	yesFetch: '是，拉取',
	fetchingBranch: '正在拉取分支',
	pullBranchConfirm: '确定要将远程分支 <b><i>{0}</i></b> 拉取(Pull)到 {1} 吗？如果需要合并：',
	yesPull: '是，拉取',
	pullingBranch: '正在拉取分支',
	applyStashConfirm: '确定要应用贮藏 <b><i>{0}</i></b> 吗？',
	popStashConfirm: '确定要弹出贮藏 <b><i>{0}</i></b> 吗？',
	reinstateIndexCheckbox: '恢复索引',
	reinstateIndexInfo: '除工作区的更改外，还尝试恢复暂存区的更改。',
	yesApplyStash: '是，应用贮藏',
	applyingStash: '正在应用贮藏',
	branchFromStashPrompt: '从贮藏 <b><i>{0}</i></b> 创建分支，名称为：',
	yesPopStash: '是，弹出贮藏',
	poppingStash: '正在弹出贮藏',
	dropStashConfirm: '<b>数据丢失风险</b>：丢弃贮藏 <b><i>{0}</i></b> 会删除其记录的更改，其 reflog 也会一并删除：贮藏提交在被 git gc 清理前只能用 <i>git fsck</i> 找回。确定要丢弃吗？',
	droppingStash: '正在丢弃贮藏',
	retrievingTagDetails: '正在获取标签详情',
	deleteTagConfirm: '<b>数据丢失风险</b>：删除标签 <b><i>{0}</i></b> 会失去对其提交的引用，重建需要知道提交哈希。确定要删除吗？',
	alsoDeleteTagOnRemote: '<br>是否同时在远程上删除该标签：',
	dontDeleteOnRemote: '不在任何远程上删除',
	alsoDeleteOnRemoteCheckbox: '同时在远程删除',
	pushTagToRemoteConfirm: '确定要将标签 <b><i>{0}</i></b> 推送到远程 <b><i>{1}</i></b> 吗？',
	pushTagSelectRemotes: '确定要推送标签 <b><i>{0}</i></b> 吗？请选择要推送到的远程：',
	pushingTag: '正在推送标签',
	stashUncommittedConfirm: '确定要贮藏<b>未提交的更改</b>吗？',
	includeUntrackedCheckbox: '包含未跟踪文件',
	includeUntrackedInfo: '将所有未跟踪文件包含在贮藏中，然后将其从工作目录中清除。',
	yesStash: '是，贮藏',
	stashingUncommitted: '正在贮藏未提交的更改',
	resetUncommittedConfirm: '确定要将<b>未提交的更改</b>重置到 <b>HEAD</b> 吗？',
	resettingUncommitted: '正在重置未提交的更改',
	cleanUntrackedConfirm: '确定要清理所有未跟踪文件吗？',
	cleanDirectoriesCheckbox: '清理未跟踪目录',
	yesClean: '是，清理',
	cleaningUntracked: '正在清理未跟踪文件',
	selectIssueToView: '选择要查看此分支的哪个 Issue：',

	/* 操作进行中提示、响应错误标题与特殊确认 */
	openingTerminal: '正在打开终端',
	pinnedCommitTitle: '已固定的提交',
	pinnedCommitNotInLoadedHistory: '在此仓库已加载的历史中找不到已固定的提交。请清除分支/路径过滤后重试。',
	pinnedCommitNotInRepo: '在此仓库中找不到已固定的提交。它可能已被变基清除，或被分支/路径过滤排除。',
	pinnedCommitNotInView: '已固定的提交当前不在视图中。请加载更多提交或清除分支/路径过滤。',
	errLoadRepoInfo: '无法加载仓库信息',
	errLoadCommits: '无法加载提交',
	noCommitsInRepo: '此仓库没有任何提交。',
	retryAction: '重试',
	unexpectedErrorHandlingMessage: '处理来自扩展的消息时发生意外错误：{0}',
	errAddRemote: '无法添加远程',
	errAddTag: '无法添加标签',
	errApplyStash: '无法应用贮藏',
	errBranchFromStash: '无法从贮藏创建分支',
	errCheckoutBranch: '无法检出分支',
	errCheckoutBranchPull: '无法检出分支并拉取更改',
	errCheckoutCommit: '无法检出提交',
	errCherryPick: '无法拣选提交',
	errCleanUntracked: '无法清理未跟踪文件',
	errCommitDetails: '无法加载提交详情',
	errCommitComparison: '无法加载提交比较',
	errCopyFilePath: '无法复制文件路径到剪贴板',
	errCopyToClipboard: '无法将{0}复制到剪贴板',
	errCreateArchive: '无法创建归档',
	errCreateBranch: '无法创建分支',
	errCreatePullRequest: '无法创建拉取请求',
	errDeleteBranch: '无法删除分支',
	errDeleteRemote: '无法删除远程',
	errDeleteRemoteBranch: '无法删除远程分支',
	errDeleteTag: '无法删除标签',
	errDeleteUserDetails: '无法移除 Git 用户信息',
	errDropCommit: '无法丢弃提交',
	errDropStash: '无法丢弃贮藏',
	errEditRemote: '无法保存远程更改',
	errEditUserDetails: '无法保存 Git 用户信息',
	errExportRepoConfig: '无法导出仓库配置',
	errFetch: '无法从远程拉取',
	errFetchIntoLocalBranch: '无法拉取到本地分支',
	errMergeActionOn: '无法合并{0}',
	errRebaseActionOn: '无法将当前分支变基到{0}',
	errOpenExtensionSettings: '无法打开扩展设置',
	errOpenLogFile: '无法打开会话日志',
	errOpenExternalDirDiff: '无法打开外部目录比较',
	errOpenExternalUrl: '无法打开外部 URL',
	errOpenFile: '无法打开文件',
	errOpenTerminal: '无法打开终端',
	errPopStash: '无法弹出贮藏',
	errPruneRemote: '无法清理远程',
	errPullBranch: '无法拉取分支',
	errPushBranch: '无法推送分支',
	errPushStash: '无法贮藏未提交的更改',
	errPushTag: '无法推送标签',
	errRenameBranch: '无法重命名分支',
	errResetFileToRevision: '无法将文件重置到该版本',
	errResetToCommit: '无法重置到提交',
	errResetLastCommit: '无法重置上一次提交',
	errRevertCommit: '无法还原提交',
	errEditCommitMessage: '无法编辑提交信息',
		errAmendCommit: '无法修改提交',
	errSaveGlobalViewState: '无法保存全局视图状态',
	errSaveWorkspaceViewState: '无法保存工作区视图状态',
	errStartCodeReview: '无法开始代码评审',
	errTagDetails: '无法获取标签详情',
	errUpdateCodeReview: '无法更新代码评审',
	errViewDiff: '无法查看差异',
	errViewDiffWithWorkingFile: '无法与工作区文件比较差异',
	errViewFileAtRevision: '无法查看该版本的文件',
	errViewScm: '无法打开源代码管理视图',
	branchNotFullyMerged: '<b>数据丢失风险</b>：分支 <b><i>{0}</i></b> 尚未完全合并，强制删除会连同该分支自己的 reflog 一起删除：其未合并的提交在被 git gc 清理前只能从本机 reflog 或 <i>git fsck</i> 找回。要强制删除它吗？',
	yesForceDeleteBranch: '是，强制删除分支',
	warnCommitNotOnRemote: '警告：提交不在远程上',
	warnCommitNotOnRemotes: '警告：提交不在远程上',
	tagCommitNotOnRemoteSingular: '标签 <b><i>{0}</i></b> 指向的提交不在远程 {1} 的任何已知分支上。',
	tagCommitNotOnRemotePlural: '标签 <b><i>{0}</i></b> 指向的提交不在远程 {1} 的任何已知分支上。',
	proceedPushTagSingular: '仍要将标签推送到远程 {0} 吗？',
	proceedPushTagPlural: '仍要将标签推送到远程 {0} 吗？',
	alwaysProceedCheckbox: '总是继续',
	proceedToPushAction: '继续推送',

	/* 提交表格、工具提示与其他 */
	globPrefix: 'Glob：{0}',
	authorsAll: '全部',
	checkedOutBranchAtCommit: '分支“{0}”当前检出到此提交。',
	commitCurrentlyCheckedOut: '此提交当前已被检出。',
	columnGraph: '图形',
	columnDescription: '描述',
	columnDate: '日期',
	columnAuthor: '作者',
	columnCommit: '提交',
	tagDetailsTitle: '标签 <b><i>{0}</i></b>',
	tagDetailsObject: '<b>对象：</b>',
	tagDetailsCommit: '<b>提交：</b>',
	tagDetailsTagger: '<b>标注者：</b>',
	tagDetailsDate: '<b>日期：</b>',
	signatureDescColon: '：',
	signatureSignedBy: '签名者：',
	signatureUnknown: '<未知>',
	signatureGpgKeyIdPrefix: '（GPG 密钥 ID：',
	signatureGpgKeyIdSuffix: '）',
	signatureStatusValid: '有效签名',
	signatureStatusUnknownValidity: '签名有效，但有效性未知',
	signatureStatusExpired: '签名有效，但已过期',
	signatureStatusExpiredKey: '签名有效，但由已过期的密钥创建',
	signatureStatusRevokedKey: '签名有效，但由已吊销的密钥创建',
	signatureStatusCouldNotBeChecked: '无法检查签名',
	signatureStatusBad: '签名无效',
	noneValue: '无',

	/* 提交详情视图、文件树及其右键菜单 */
	loadingCommitDetails: '正在加载提交详情...',
	loadingUncommittedChanges: '正在加载未提交的更改...',
	loadingCommitComparison: '正在加载提交比较...',
	cdvCommitLabel: '<b>提交：</b>',
	cdvParentsLabel: '<b>父提交：</b>',
	cdvAuthorLabel: '<b>作者：</b>',
	cdvAuthorDateLabel: '<b>作者日期：</b>',
	cdvCommitterLabel: '<b>提交者：</b>',
	cdvDateLabel: '<b>日期：</b>',
	cdvCommitterDateLabel: '<b>提交者日期：</b>',
	displayingUncommitted: '显示所有未提交的更改。',
	displayingChangesFromTo: '显示从 <b>{0}</b> 到 <b>{1}</b> 的所有更改。',
	uncommittedChangesLabel: '未提交的更改',
	uncommittedChangesRow: '未提交的更改（{0}）',
	fileListViewTitle: '文件列表视图',
	fileTreeViewTitle: '文件树视图',
	collapseFoldersTitle: '折叠/展开文件夹',
	expandFoldersTitle: '展开文件夹',
	lastFileViewedTitle: '最后查看的文件',
	resetFileConfirm: '确定要将 <b><i>{0}</i></b> 重置到它在提交 <b><i>{1}</i></b> 时的状态吗？该文件所有未提交的更改将被覆盖。',
	yesResetFile: '是，重置文件',
	resettingFile: '正在重置文件',
	cdvMenuViewDiff: '查看差异',
	cdvMenuViewFileAtRevision: '查看该版本的文件',
	cdvMenuViewDiffWithWorkingFile: '与工作区文件比较差异',
	cdvMenuOpenFile: '打开文件',
	cdvMenuMarkReviewed: '标记为已评审',
	cdvMenuMarkNotReviewed: '标记为未评审',
	cdvMenuResetFileToRevision: '将文件重置到该版本',
	cdvMenuCopyAbsolutePath: '复制绝对文件路径到剪贴板',
	cdvMenuCopyRelativePath: '复制相对文件路径到剪贴板',
	externalDiffTitle: '打开外部目录比较',
	externalDiffWithTool: '（工具：“{0}”）',
	startCodeReviewTitle: '开始代码评审',
	endCodeReviewTitle: '结束代码评审',
	changeTypeAdded: '新增',
	changeTypeModified: '修改',
	changeTypeDeleted: '删除',
	changeTypeRenamed: '重命名',
	changeTypeUntracked: '未跟踪',
	clickToViewDiff: '点击查看差异',
	unableToViewDiff: '无法查看差异',
	binaryFileSuffix: '（这是二进制文件）',
	additionSingular: '{0} 处新增',
	additionPlural: '{0} 处新增',
	deletionSingular: '{0} 处删除',
	deletionPlural: '{0} 处删除',
	clickToViewRepo: '点击查看仓库',

	/* URL 与列头右键菜单、图形工具提示、下拉列表与查找挂件 */
	menuOpenUrl: '打开 URL',
	menuFollowInternalLink: '打开内部链接',
	menuCopyUrl: '复制 URL 到剪贴板',
	orderCommitTimestamp: '按提交时间排序',
	orderAuthorTimestamp: '按作者时间排序',
	orderTopological: '按拓扑排序',
	graphTooltipCommit: '提交 {0}',
	graphTooltipThisCommitIs: '此提交',
	graphTooltipNot: '<b><i>不</i></b>',
	graphTooltipIncludedInHead: '包含在 <span class="graphTooltipRef">HEAD</span> 中',
	graphTooltipBranches: '分支：',
	graphTooltipTags: '标签：',
	graphTooltipStashes: '贮藏：',
	filterDropdownPlaceholder: '过滤{0}...',
	dropdownNoResults: '未找到结果。',
	findZeroLengthMatch: '不能使用会产生零长度匹配的正则表达式'
};

/**
 * The currently active string dictionary (module-global, read by all web sources).
 */
let strings: WebviewStrings = STRINGS_EN;

/**
 * The currently active interface language code (tracked alongside `strings` so helpers like the
 * date formatters can vary their format, not just their labels, per language).
 */
let interfaceLanguage = 'en';

/**
 * Get the interface language currently applied to the webview.
 * @returns The language code ('en' or 'zh-cn').
 */
function getInterfaceLanguage(): string {
	return interfaceLanguage;
}

/**
 * Get the string dictionary for an interface language.
 * @param lang The language code ('en' or 'zh-cn'; anything else falls back to English).
 */
function getStrings(lang: string): WebviewStrings {
	return lang === 'zh-cn' ? STRINGS_ZH_CN : STRINGS_EN;
}

/**
 * Switch the active string dictionary (called during webview start-up).
 * @param lang The language code ('en' or 'zh-cn').
 */
function setInterfaceLanguage(lang: string) {
	strings = getStrings(lang);
	interfaceLanguage = lang === 'zh-cn' ? 'zh-cn' : 'en';
}

/**
 * Substitute {0}, {1}, ... placeholders in a string from the active dictionary.
 * @param template The template string.
 * @param args The values to substitute.
 */
function formatStr(template: string, ...args: string[]): string {
	return template.replace(/\{(\d+)\}/g, (match, index) => typeof args[index] === 'string' ? args[index] : match);
}
